package tools

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/kaptinlin/jsonrepair"
)

// NormalizeJSONInput ensures tool input is valid JSON before decoding.
// Empty input is normalized to an empty object so tools with optional
// parameters can omit arguments safely.
func NormalizeJSONInput(input string) (string, error) {
	trimmed := strings.TrimSpace(input)
	if trimmed == "" {
		return "{}", nil
	}

	if json.Valid([]byte(trimmed)) {
		return trimmed, nil
	}

	repaired, err := jsonrepair.JSONRepair(trimmed)
	if err != nil {
		return "", fmt.Errorf("repair json input: %w", err)
	}

	repaired = strings.TrimSpace(repaired)
	if repaired == "" {
		return "", fmt.Errorf("repair json input: empty result")
	}
	if !json.Valid([]byte(repaired)) {
		return "", fmt.Errorf("repair json input: repaired output is still invalid json")
	}

	return repaired, nil
}

// DecodeToolInput normalizes malformed JSON generated by models and decodes it
// into the provided target structure.
func DecodeToolInput(input string, target any) error {
	normalized, err := NormalizeJSONInput(input)
	if err != nil {
		return fmt.Errorf("error parsing parameters: %w", err)
	}
	if err := json.Unmarshal([]byte(normalized), target); err != nil {
		return fmt.Errorf("error parsing parameters: %w", err)
	}
	return nil
}

// MustNormalizeToolCallInput returns a copy of the call with normalized JSON input.
func MustNormalizeToolCallInput(call ToolCall) (ToolCall, error) {
	normalized, err := NormalizeJSONInput(call.Input)
	if err != nil {
		return ToolCall{}, fmt.Errorf("error parsing parameters: %w", err)
	}
	call.Input = normalized
	return call, nil
}
