// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetsHandler() {
  return window['go']['desktop']['App']['AssetsHandler']();
}

export function GetServerInfo() {
  return window['go']['desktop']['App']['GetServerInfo']();
}

export function GetVersion() {
  return window['go']['desktop']['App']['GetVersion']();
}

export function OpenFileDialog(arg1) {
  return window['go']['desktop']['App']['OpenFileDialog'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['desktop']['App']['OpenInBrowser'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['desktop']['App']['SaveFileDialog'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['desktop']['App']['SelectDirectory']();
}

export function ShowMessageDialog(arg1, arg2) {
  return window['go']['desktop']['App']['ShowMessageDialog'](arg1, arg2);
}

export function WindowMaximise() {
  return window['go']['desktop']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['desktop']['App']['WindowMinimise']();
}

export function WindowSetTitle(arg1) {
  return window['go']['desktop']['App']['WindowSetTitle'](arg1);
}

export function WindowToggleMaximise() {
  return window['go']['desktop']['App']['WindowToggleMaximise']();
}
