// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function AssetsHandler():Promise<http.Handler>;

export function GetServerInfo():Promise<Record<string, string>>;

export function GetVersion():Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function ShowMessageDialog(arg1:string,arg2:string):Promise<string>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowSetTitle(arg1:string):Promise<void>;

export function WindowToggleMaximise():Promise<void>;
