/**
 * Wails desktop config helpers.
 *
 * Detection itself lives in @pando/client/services/host, which every frontend
 * shares. What stays here is the part that imports the Wails bindings this
 * repository generates, which a shared package cannot reach.
 */

import { isDesktop, type PandoDesktopConfig } from '@pando/client/services/host'

export { isDesktop }
export type { PandoDesktopConfig }

/**
 * In desktop mode, fetches server info (URL + token) from the Go binding.
 * Returns null in web mode.
 */
export async function getDesktopConfig(): Promise<PandoDesktopConfig | null> {
  if (!isDesktop) return null
  try {
    // Dynamically import the Wails-generated binding to avoid errors in web mode.
    // The file is generated by `wails build` / `wails dev` into wailsjs/go/desktop/App.js
    const { GetServerInfo } = await import('../../wailsjs/go/desktop/App')
    return (await GetServerInfo()) as unknown as PandoDesktopConfig
  } catch {
    // Wails bindings not available yet — fall back to window.__PANDO__ if injected
    const w = window as unknown as Record<string, unknown>
    if (w.__PANDO__) return w.__PANDO__ as PandoDesktopConfig
    return null
  }
}
