/**
 * Wails desktop detection and config helpers.
 * In the Wails WebView, the runtime injects `window.go` namespace.
 */

export interface PandoDesktopConfig {
  apiBase: string
  token: string
}

/** True when running inside the Wails desktop WebView. */
export const isDesktop: boolean =
  typeof window !== 'undefined' && 'go' in (window as unknown as Record<string, unknown>)

/**
 * In desktop mode, fetches server info (URL + token) from the Go binding.
 * Returns null in web mode.
 */
export async function getDesktopConfig(): Promise<PandoDesktopConfig | null> {
  if (!isDesktop) return null
  try {
    // Dynamically import the Wails-generated binding to avoid errors in web mode.
    // The file is generated by `wails build` / `wails dev` into wailsjs/go/desktop/App.js
    const { GetServerInfo } = await import('../../wailsjs/go/desktop/App')
    return (await GetServerInfo()) as unknown as PandoDesktopConfig
  } catch {
    // Wails bindings not available yet — fall back to window.__PANDO__ if injected
    const w = window as unknown as Record<string, unknown>
    if (w.__PANDO__) return w.__PANDO__ as PandoDesktopConfig
    return null
  }
}
