package luaengine

import "time"

// FilterType represents the type of filter (input or output)
type FilterType string

const (
	// FilterInput processes parameters before tool execution
	FilterInput FilterType = "input"
	// FilterOutput processes results after tool execution
	FilterOutput FilterType = "output"
)

// HookType represents the type of lifecycle hook
type HookType string

const (
	HookSystemPrompt        HookType = "system_prompt"
	HookSessionStart        HookType = "session_start"
	HookSessionRestore      HookType = "session_restore"
	HookConversationStart   HookType = "conversation_start"
	HookUserPrompt          HookType = "user_prompt"
	HookAgentResponseFinish HookType = "agent_response_finish"

	// Template system hooks
	HookTemplateSection HookType = "template_section"
	HookCapabilityCheck HookType = "capability_check"
	HookProviderSelect  HookType = "provider_select"
	HookPromptCompose   HookType = "prompt_compose"
)

// HookContext contains the context information passed to Lua filter functions.
// This structure is converted to a Lua table and passed to filter functions.
type HookContext struct {
	// ServerName is the name of the downstream MCP server
	ServerName string `json:"server_name"`

	// ToolName is the name of the tool being executed
	ToolName string `json:"tool_name"`

	// HookType indicates the lifecycle hook type (for ExecuteHook)
	HookType HookType `json:"hook_type,omitempty"`

	// Parameters contains the input parameters (for input filters)
	Parameters map[string]interface{} `json:"parameters,omitempty"`

	// Result contains the execution result (for output filters)
	Result map[string]interface{} `json:"result,omitempty"`

	// RequestID is a unique identifier for this request
	RequestID string `json:"request_id"`

	// SessionID is the current session identifier
	SessionID string `json:"session_id,omitempty"`

	// Timestamp is when the hook was triggered
	Timestamp int64 `json:"timestamp"`

	// Duration is the execution time in milliseconds (for output filters only)
	Duration int64 `json:"duration,omitempty"`

	// FilterType indicates whether this is an input or output filter
	FilterType FilterType `json:"filter_type"`
}

// HookResult represents the result of applying a filter or executing a hook.
type HookResult struct {
	// Modified indicates whether the filter made any changes
	Modified bool

	// Data contains the filtered data (parameters or result)
	Data map[string]interface{}

	// Error contains any error that occurred during filter execution
	Error error

	// ExecutionTime is how long the filter took to execute
	ExecutionTime time.Duration

	// Logs contains any log messages generated by the filter
	Logs []string
}

// NewInputContext creates a new HookContext for an input filter.
func NewInputContext(serverName, toolName string, parameters map[string]interface{}, requestID string) *HookContext {
	return &HookContext{
		ServerName: serverName,
		ToolName:   toolName,
		Parameters: parameters,
		RequestID:  requestID,
		Timestamp:  time.Now().Unix(),
		FilterType: FilterInput,
	}
}

// NewOutputContext creates a new HookContext for an output filter.
func NewOutputContext(serverName, toolName string, result map[string]interface{}, requestID string, duration time.Duration) *HookContext {
	return &HookContext{
		ServerName: serverName,
		ToolName:   toolName,
		Result:     result,
		RequestID:  requestID,
		Timestamp:  time.Now().Unix(),
		Duration:   duration.Milliseconds(),
		FilterType: FilterOutput,
	}
}

// NewHookResult creates a new HookResult with default values.
func NewHookResult() *HookResult {
	return &HookResult{
		Modified: false,
		Data:     make(map[string]interface{}),
		Logs:     make([]string, 0),
	}
}
