package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/digiogithub/pando/internal/config"
	"github.com/digiogithub/pando/internal/logging"
	"github.com/spf13/cobra"
)

// defaultConfigTemplate is the annotated .pando.toml written by "pando init".
// Each section includes comments explaining the available options.
const defaultConfigTemplate = `# =============================================================================
# Pando Configuration File
# Generated by 'pando init'
#
# Pando looks for this file in (highest priority first):
#   1. Current working directory  (.pando.toml)
#   2. $HOME/.config/pando/.pando.toml
#   3. $HOME/.pando.toml
#
# Environment variables prefixed with PANDO_ override any value here.
# Example: PANDO_DEBUG=true overrides Debug = false
# =============================================================================

# Working directory override. Leave empty to use the directory where pando runs.
WorkingDir = ''

# Enable verbose debug logging to stderr (or LogFile when set).
Debug = false

# Path to a log file for debug output. Useful for CI or headless environments.
# Example: LogFile = '/tmp/pando-debug.log'
LogFile = ''

# Enable debug logging for LSP (Language Server Protocol) clients.
DebugLSP = false

# Additional paths to include in the AI context window (relative or absolute).
# Example: ContextPaths = ['./docs', './specs']
ContextPaths = []

# Automatically compact the conversation context when it approaches the model
# token limit. Recommended: true for long sessions.
AutoCompact = true

# =============================================================================
# Data Storage
# =============================================================================
[Data]
# Directory for databases, session history, and other persistent data.
# Relative paths are resolved from WorkingDir.
Directory = './.pando/data'

# =============================================================================
# MCP Servers (Model Context Protocol)
# MCP servers extend Pando with external tools (search, databases, browsers…).
# Each entry is a named server. Supported types: stdio | sse | streamable-http
# =============================================================================
# [MCPServers]

# --- stdio example (local process) ---
# [MCPServers.my-local-tool]
# Type    = 'stdio'
# Command = 'my-mcp-server'
# Args    = ['--flag', 'value']
# Env     = ['MY_VAR=hello']

# --- HTTP example (remote or local HTTP service) ---
# [MCPServers.remembrances]
# Type = 'streamable-http'
# URL  = 'http://127.0.0.1:4030/mcp'

# =============================================================================
# LLM Providers
# Configure API keys and base URLs for each provider you want to use.
# At least one provider must be enabled for Pando to function.
# =============================================================================
[Providers]

# Anthropic (Claude models). Set APIKey or enable OAuth for claude.ai login.
[Providers.anthropic]
APIKey   = ''    # ANTHROPIC_API_KEY env var also accepted
BaseURL  = ''    # Override only if using a proxy; leave empty for official API
Disabled = false
UseOAuth = true  # Use claude.ai OAuth instead of a raw API key

# OpenAI — uncomment and add your key to enable.
# [Providers.openai]
# APIKey   = ''  # OPENAI_API_KEY env var also accepted
# Disabled = false

# GitHub Copilot — uses the Copilot API (requires Copilot subscription).
# [Providers.copilot]
# Disabled = false

# Ollama (local models, no API key required).
# [Providers.ollama]
# BaseURL  = 'http://localhost:11434'
# Disabled = false

# =============================================================================
# Language Server Protocol (LSP)
# LSP servers provide code intelligence (completions, diagnostics, etc.).
# Pando starts them automatically for supported file types.
# =============================================================================
[LSP]

# Go language server. Remove or set Disabled = true if you don't use Go.
[LSP.gopls]
Disabled  = false
Command   = 'gopls'
Args      = []
Languages = []  # Leave empty to apply to all files; e.g. ['.go']

# TypeScript / JavaScript (requires typescript-language-server in PATH).
# [LSP.ts]
# Disabled  = false
# Command   = 'typescript-language-server'
# Args      = ['--stdio']
# Languages = ['.ts', '.tsx', '.js', '.jsx']

# =============================================================================
# Agents
# Each agent uses a specific LLM model for a particular role.
# Model format: '<provider>.<model-id>'   e.g. 'anthropic.claude-sonnet-4-6'
# =============================================================================
[Agents]

# Primary coding assistant — handles most interactive and non-interactive tasks.
[Agents.coder]
Model                 = 'anthropic.claude-sonnet-4-6'
MaxTokens             = 32000
ReasoningEffort       = ''     # 'low' | 'medium' | 'high' (OpenAI o-series only)
AutoCompact           = false
AutoCompactThreshold  = 0.0    # 0.0 = use global AutoCompact setting

# Summariser — condenses long conversations to save tokens.
[Agents.summarizer]
Model     = 'anthropic.claude-sonnet-4-6'
MaxTokens = 90000

# Task planner — breaks large goals into steps (used by the orchestrator).
[Agents.task]
Model           = 'anthropic.claude-sonnet-4-6'
MaxTokens       = 16384
ReasoningEffort = 'low'

# =============================================================================
# Skills (reusable agent prompts / slash-commands)
# =============================================================================
[Skills]
# Enable the skills system.
Enabled = true
# Directories to scan for skill definition files (*.md / *.lua).
Paths = ['./agents/skills']

# Skills catalog — remote registry of shared skills (disabled by default).
[SkillsCatalog]
Enabled     = false
BaseURL     = ''
AutoUpdate  = false
DefaultScope = ''

# =============================================================================
# TUI (Terminal User Interface)
# =============================================================================
[TUI]
# Theme name (leave empty for the built-in default).
# Run 'pando themes' to list available themes.
Theme = ''

# =============================================================================
# Permissions
# Controls whether the assistant should ask before applying tool-based file edits.
# =============================================================================
[Permissions]
# true  = apply file/tool changes directly without per-action confirmation
# false = require confirmation before applying file/tool changes (default)
AutoApproveTools = false

# =============================================================================
# Mesnada — Multi-Agent Orchestrator
# Mesnada lets you spawn and coordinate multiple AI agents in parallel.
# =============================================================================
[Mesnada]
Enabled = true

# Internal gRPC/HTTP server used by agents to communicate with the orchestrator.
[Mesnada.Server]
Host = ''     # Leave empty to bind to localhost
Port = 5005

[Mesnada.Orchestrator]
StorePath      = './.pando/mesnada/tasks.json' # Task store file (JSON)
LogDir         = './.pando/mesnada/logs'     # Task execution logs
MaxParallel    = 5                           # Maximum concurrent sub-agents
DefaultEngine  = 'claude'                    # Default AI engine: 'claude' | 'copilot'
DefaultModel   = 'sonnet'                    # Default model shorthand
# DefaultMCPConfig is optional. When unset, pando generates a dynamic MCP config
# that includes pando itself plus any MCPServers defined in this file.
# DefaultMCPConfig = '/path/to/custom-mcp-config.json'
PersonaPath    = './.pando/mesnada/personas' # Directory of persona definition files

# ACP (Agent Client Protocol) — lets VS Code / Zed / JetBrains talk to Pando.
[Mesnada.ACP]
Enabled        = true
DefaultAgent   = 'claude'
AutoPermission = true   # Auto-approve tool calls when running as an ACP agent

[Mesnada.ACP.Server]
Enabled        = false       # Expose an ACP HTTP server (for remote IDE integration)
Transports     = ['http']
Host           = '0.0.0.0'
Port           = 8766
MaxSessions    = 100
SessionTimeout = '30m'
RequireAuth    = false

[Mesnada.TUI]
Enabled = true
WebUI   = false

# =============================================================================
# Shell & Bash tool configuration
# =============================================================================
[Shell]
Path = ''   # Override default shell (empty = auto-detect from $SHELL)
Args = []

[Bash]
# Commands that the AI is never allowed to run, regardless of permissions.
BannedCommands  = []
# When non-empty, only these commands are allowed (whitelist mode).
AllowedCommands = []

# =============================================================================
# Remembrances — Semantic memory and knowledge-base integration
# Requires an embedding server (Ollama recommended for local, zero-cost usage).
# =============================================================================
[Remembrances]
Enabled = true

# Optional local KB mirror/sync directory. When set, pando can import .md files
# recursively from this path and keep DB/filesystem synchronized.
KBPath = ''

# Import markdown files from KBPath on startup.
KBAutoImport = true

# Watch KBPath in real-time and reindex changed/created/deleted .md files.
KBWatch = true

# Embedding model for documents (markdown, text files).
DocumentEmbeddingProvider = 'ollama'
DocumentEmbeddingModel    = 'nomic-embed-text'
DocumentEmbeddingBaseURL  = ''   # Override for remote Ollama; empty = localhost
DocumentEmbeddingAPIKey   = ''

# Embedding model for source code. A code-focused model gives better results.
CodeEmbeddingProvider = 'ollama'
CodeEmbeddingModel    = 'hf.co/limcheekin/CodeRankEmbed-GGUF:Q4_K_M'
CodeEmbeddingBaseURL  = ''
CodeEmbeddingAPIKey   = ''

# Use the same model for both document and code embeddings (simpler setup).
UseSameModel = false

# Chunking parameters — tune these if search recall feels off.
ChunkSize    = 800
ChunkOverlap = 100

# Number of parallel workers used when indexing large projects.
IndexWorkers = 4

# =============================================================================
# API Server (Web UI backend)
# =============================================================================
[Server]
Enabled     = true
Host        = 'localhost'
Port        = 9999
RequireAuth = false

# =============================================================================
# Lua scripting — hook into Pando events with custom Lua scripts.
# =============================================================================
[Lua]
Enabled          = false
ScriptPath       = ''    # Path to your main Lua hook file
Timeout          = ''    # e.g. '5s' — max execution time per hook call
StrictMode       = false # Fail on unknown hooks; false = warn only
HotReload        = false # Reload script on file change (development convenience)
LogFilteredData  = false

# =============================================================================
# MCP Gateway — intelligent routing & caching for MCP tool calls
# =============================================================================
[MCPGateway]
Enabled             = true
FavoriteThreshold   = 3   # Calls before a tool is marked as "favourite"
MaxFavorites        = 10
FavoriteWindowDays  = 7
DecayDays           = 30  # Days of inactivity before a favourite is demoted

# =============================================================================
# Internal Tools — optional built-in tools exposed to the AI
# Each requires an API key from the respective service.
# =============================================================================
[InternalTools]
FetchEnabled          = false   # Allow the AI to fetch URLs
FetchMaxSizeMB        = 0
GoogleSearchEnabled   = false
GoogleAPIKey          = ''
GoogleSearchEngineID  = ''
BraveSearchEnabled    = false
BraveAPIKey           = ''
PerplexitySearchEnabled = false
PerplexityAPIKey        = ''
ExaSearchEnabled      = false
ExaAPIKey             = ''
Context7Enabled       = false
BrowserEnabled        = false
BrowserHeadless       = false
BrowserTimeout        = 30
BrowserUserDataDir    = ''
BrowserMaxSessions    = 3

# =============================================================================
# Snapshots — lightweight point-in-time backups of your working directory
# =============================================================================
[Snapshots]
Enabled           = true
MaxSnapshots      = 50
MaxFileSize       = '10MB'        # Files larger than this are skipped
ExcludePatterns   = []            # Glob patterns to exclude (e.g. 'node_modules/**')
AutoCleanupDays   = 30

# =============================================================================
# Evaluator — LLM-as-Judge self-improvement loop
# After each session the evaluator scores the interaction and uses UCB1 to
# select better prompt templates over time.
# =============================================================================
[evaluator]
# Enable the evaluation loop.
enabled = true

# Judge model: use a fast/cheap model — it only needs to score conversations.
model    = 'anthropic.claude-haiku-4-5-20251001'
provider = 'anthropic'

# Reward formula: R = alphaWeight * S_success + betaWeight * S_efficiency
# S_success degrades 0.3 per detected user correction; S_efficiency measures
# token usage relative to a rolling baseline.
alphaWeight = 0.8   # Weight for task-quality score  (0.0–1.0)
betaWeight  = 0.2   # Weight for efficiency score    (0.0–1.0)

# UCB1 exploration factor — sqrt(2) ≈ 1.41 is the theoretical optimum.
# Higher values try new prompt templates more aggressively.
explorationC = 1.41

# Minimum evaluated sessions before UCB template selection activates.
minSessionsForUCB = 5

# Rolling window (sessions) for computing the token-efficiency baseline.
maxTokensBaseline = 50

# Maximum skills kept in the skill library (oldest/lowest-scoring pruned).
maxSkills = 100

# Run evaluation asynchronously after session end (recommended).
async = true

# Custom judge prompt template file (leave empty to use the built-in prompt).
judgePromptTemplate = ''

# Phrases that indicate the user corrected the AI — each match lowers S_success.
# Includes English and Spanish patterns, as well as scope/constraint violation signals.
correctionsPatterns = [
  # English — generic correction signals
  '(?i)\\bwrong\\b',
  '(?i)\\bincorrect\\b',
  "(?i)that'?s not",
  '(?i)not what i',
  '(?i)\\bmistake\\b',
  '(?i)\\bfix that\\b',
  "(?i)\\bdon'?t do that\\b",
  '(?i)\\bstop doing\\b',
  "(?i)\\bthat'?s not right\\b",
  '(?i)\\bnot what i asked\\b',
  "(?i)\\byou'?re wrong\\b",
  '(?i)\\byou missed\\b',
  "(?i)\\bthat'?s wrong\\b",
  # English — scope/constraint violation signals
  '(?i)\\bdo it directly\\b',
  '(?i)\\bno script\\b',
  "(?i)\\bdon'?t generate\\b",
  "(?i)\\bi said don'?t\\b",
  # Spanish — generic correction signals
  '(?i)\\barréglalo\\b',
  '(?i)\\bno era eso\\b',
  '(?i)\\bno lo hagas\\b',
  '(?i)\\basí no\\b',
  '(?i)\\bestá mal\\b',
  '(?i)\\beso no es\\b',
  '(?i)\\bte equivocaste\\b',
  '(?i)\\bvuelve a\\b',
  '(?i)\\bno hagas\\b',
  '(?i)\\beso no era\\b',
  '(?i)\\bno es correcto\\b',
  # Spanish — scope/constraint violation signals
  '(?i)\\bhazlo directamente\\b',
  '(?i)\\bno hagas ningún script\\b',
  '(?i)\\bno intentes\\b',
]

# =============================================================================
# CLI Assist — one-shot AI helper for shell command suggestions
# =============================================================================
[cliAssist]
Model   = ''   # Leave empty to use the coder agent model
Timeout = 0    # Seconds; 0 = no timeout

# =============================================================================
# Persona Auto-Select — automatically pick a persona based on project context
# =============================================================================
[PersonaAutoSelect]
Enabled     = false
PersonaPath = ''    # Directory of persona files to select from

# =============================================================================
# ACP (Agent Client Protocol) — legacy standalone config block
# =============================================================================
[acp]
enabled         = false
max_sessions    = 0
idle_timeout    = ''
log_level       = ''
auto_permission = false
`

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a Pando configuration with recommended settings",
	Long: `Initialize Pando by creating a configuration file (.pando.toml) and the
required directory structure.

Two initialization targets are available:

  project  — creates .pando.toml and .pando/ in the current directory (or the
             directory specified with --cwd). Use this for per-project settings.

  profile  — creates .pando.toml and ~/.config/pando/ in your home profile.
             Use this for global defaults shared across all projects.

If no --target flag is provided the command will ask interactively.`,
	Example: `
  # Interactive — asks where to initialise
  pando init

  # Directly target the current project
  pando init --target project

  # Directly target the global user profile
  pando init --target profile

  # Initialise a specific directory without prompting
  pando init --target project --cwd /path/to/my-project

  # Overwrite an existing configuration
  pando init --force`,
	RunE: func(cmd *cobra.Command, args []string) error {
		target, _ := cmd.Flags().GetString("target")
		force, _ := cmd.Flags().GetBool("force")
		cwd, _ := cmd.Flags().GetString("cwd")

		// Resolve working directory.
		if cwd != "" {
			if err := os.Chdir(cwd); err != nil {
				return fmt.Errorf("failed to change directory: %w", err)
			}
		}
		currentDir, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("failed to get current working directory: %w", err)
		}

		// Ask the user interactively if no --target flag was given.
		if target == "" {
			target, err = askInitTarget(currentDir)
			if err != nil {
				return err
			}
		}

		switch strings.ToLower(target) {
		case "project", "p":
			return runProjectInit(currentDir, force)
		case "profile", "g", "global":
			return runProfileInit(force)
		default:
			return fmt.Errorf("unknown target %q — use 'project' or 'profile'", target)
		}
	},
}

// askInitTarget prompts the user to choose between project and profile init.
func askInitTarget(currentDir string) (string, error) {
	fmt.Println()
	fmt.Println("Where would you like to initialise Pando?")
	fmt.Println()
	fmt.Printf("  [1] project  — current directory (%s)\n", currentDir)
	fmt.Println("  [2] profile  — global user profile (~/.config/pando/)")
	fmt.Println()
	fmt.Print("Enter choice [1/2] (default: 1): ")

	reader := bufio.NewReader(os.Stdin)
	line, err := reader.ReadString('\n')
	if err != nil {
		return "", fmt.Errorf("failed to read input: %w", err)
	}

	choice := strings.TrimSpace(line)
	switch choice {
	case "", "1", "project", "p":
		return "project", nil
	case "2", "profile", "g", "global":
		return "profile", nil
	default:
		return "", fmt.Errorf("invalid choice %q — enter 1 or 2", choice)
	}
}

// runProjectInit initialises Pando in the given project directory.
func runProjectInit(projectDir string, force bool) error {
	fmt.Printf("\nInitialising Pando project in: %s\n\n", projectDir)

	configPath := filepath.Join(projectDir, ".pando.toml")
	dataDir := filepath.Join(projectDir, ".pando", "data")
	mesnadaDir := filepath.Join(projectDir, ".pando", "mesnada")
	logsDir := filepath.Join(mesnadaDir, "logs")
	personasDir := filepath.Join(mesnadaDir, "personas")
	skillsDir := filepath.Join(projectDir, "agents", "skills")

	dirs := []string{dataDir, logsDir, personasDir, skillsDir}
	if err := createDirs(dirs); err != nil {
		return err
	}

	if err := writeConfigFile(configPath, force); err != nil {
		return err
	}

	defaultPersona := filepath.Join(personasDir, "default.md")
	if err := writePersonaFile(defaultPersona, force); err != nil {
		return err
	}

	// Mark the project as initialised so the TUI skips the first-run dialog.
	initFlag := filepath.Join(dataDir, "init")
	if err := touchFile(initFlag); err != nil {
		logging.Debug("Could not write init flag file", "err", err)
	}

	printSuccess("project", configPath, dirs)
	return nil
}

// runProfileInit initialises Pando in the user's global profile directory.
func runProfileInit(force bool) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to determine home directory: %w", err)
	}

	profileDir := filepath.Join(homeDir, ".config", "pando")
	configPath := filepath.Join(profileDir, ".pando.toml")
	dataDir := filepath.Join(profileDir, "data")
	personasDir := filepath.Join(profileDir, "personas")
	skillsDir := filepath.Join(profileDir, "skills")

	fmt.Printf("\nInitialising Pando global profile in: %s\n\n", profileDir)

	dirs := []string{profileDir, dataDir, personasDir, skillsDir}
	if err := createDirs(dirs); err != nil {
		return err
	}

	if err := writeConfigFile(configPath, force); err != nil {
		return err
	}

	defaultPersona := filepath.Join(personasDir, "default.md")
	if err := writePersonaFile(defaultPersona, force); err != nil {
		return err
	}

	printSuccess("profile", configPath, dirs)
	return nil
}

// createDirs creates the given directories (and all parents) with 0755 permissions.
func createDirs(dirs []string) error {
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", d, err)
		}
		fmt.Printf("  created  %s\n", d)
	}
	return nil
}

// writeConfigFile writes the annotated default config to path.
// Returns an error if the file already exists and force is false.
func writeConfigFile(path string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		fmt.Printf("  skipped  %s  (already exists — use --force to overwrite)\n", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(defaultConfigTemplate), 0644); err != nil {
		return fmt.Errorf("failed to write config file %s: %w", path, err)
	}
	fmt.Printf("  created  %s\n", path)
	return nil
}

// writePersonaFile writes the starter persona to path.
// Skips silently if the file exists and force is false.
func writePersonaFile(path string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		fmt.Printf("  skipped  %s  (already exists)\n", path)
		return nil
	}
	if err := os.WriteFile(path, []byte(config.DefaultPersonaTemplate), 0644); err != nil {
		return fmt.Errorf("failed to write persona file %s: %w", path, err)
	}
	fmt.Printf("  created  %s\n", path)
	return nil
}

// touchFile creates an empty file (or updates its timestamp if it exists).
func touchFile(path string) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	return f.Close()
}

// printSuccess prints the final summary after successful initialisation.
func printSuccess(target, configPath string, dirs []string) {
	fmt.Println()
	fmt.Printf("Pando %s initialised successfully.\n", target)
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Printf("  1. Edit %s to configure your providers and API keys.\n", configPath)
	fmt.Println("  2. Add persona files to the personas/ directory to customise agent behaviour.")
	fmt.Println("  3. Run 'pando' to start the interactive assistant.")
	fmt.Println()
}

func init() {
	rootCmd.AddCommand(initCmd)

	initCmd.Flags().StringP("target", "t", "", "Initialisation target: 'project' (current directory) or 'profile' (global ~/.config/pando/)")
	initCmd.Flags().StringP("cwd", "c", "", "Working directory (defaults to current directory, only for --target project)")
	initCmd.Flags().Bool("force", false, "Overwrite existing configuration files")
}
