package design

import (
	"context"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/digiogithub/pando/internal/design/preview"
)

// Presentation is what a surface needs to show an artifact to the user: where
// to open it, which slide, and which element is selected.
//
// URL is a file:// address until the preview server exists; every surface reads
// it from here, so pointing them all at the served preview later is a change in
// one place.
type Presentation struct {
	ArtifactID string `json:"artifact_id"`
	Title      string `json:"title"`
	Kind       Kind   `json:"kind"`
	Version    int    `json:"version"`
	// Dir and Entry are project-relative.
	Dir   string `json:"dir"`
	Entry string `json:"entry"`
	// URL is the address to open. It is a served preview URL whenever a preview
	// server is running in this process, and a file:// address otherwise, so a
	// surface never has to ask which mode it is in.
	URL string `json:"url"`
	// FileURL is always the file:// address of the entry document. Exports and
	// "reveal in file manager" want the file, not the server.
	FileURL string `json:"file_url"`
	// BridgeURL is the preview URL with the selection bridge enabled. Only the
	// Pando UI loads it: it is what makes click-to-select work in the iframe.
	// Empty when no preview server is running.
	BridgeURL string `json:"bridge_url,omitempty"`
	// Slides is the deck slide count, zero for other kinds.
	Slides int `json:"slides,omitempty"`
	// Slide is the slide to open at, zero when unset.
	Slide int `json:"slide,omitempty"`
	// Selection is the design://<node_id> reference of the focused element.
	Selection string `json:"selection,omitempty"`
}

// Presentation resolves how an artifact should be shown. A node id is validated
// against the current index so a surface never receives a selection it cannot
// resolve.
func (s *Service) Presentation(ctx context.Context, artifactID string, slide int, nodeID string) (Presentation, error) {
	artifact, err := s.store.GetArtifact(ctx, artifactID)
	if err != nil {
		return Presentation{}, err
	}
	absDir, err := s.layout.AbsDir(artifact.Dir)
	if err != nil {
		return Presentation{}, err
	}
	manifest, err := ReadManifest(absDir)
	if err != nil {
		return Presentation{}, err
	}

	p := Presentation{
		ArtifactID: artifact.ID,
		Title:      artifact.Title,
		Kind:       artifact.Kind,
		Version:    artifact.CurrentVersion,
		Dir:        artifact.Dir,
		Entry:      filepath.ToSlash(filepath.Join(artifact.Dir, manifest.Entry)),
	}
	if manifest.Deck != nil {
		p.Slides = manifest.Deck.Slides
	}
	if slide > 0 {
		p.Slide = slide
	}

	entryPath := filepath.Join(absDir, filepath.FromSlash(manifest.Entry))
	if _, err := os.Stat(entryPath); err != nil {
		return Presentation{}, fmt.Errorf("design: entry document %s is missing: %w", p.Entry, err)
	}
	u := &url.URL{Scheme: "file", Path: filepath.ToSlash(entryPath)}
	if p.Slide > 0 {
		u.Fragment = fmt.Sprintf("slide-%d", p.Slide)
	}
	p.URL = u.String()
	p.FileURL = p.URL

	// A running preview server wins: served HTTP is the only mode where the
	// bridge, remote access and relative asset URLs all behave.
	if server := PreviewServer(); server != nil {
		if grant, err := s.publishPreviewOn(server, artifact); err == nil {
			if served, err := server.URL(grant.ArtifactID, preview.URLOptions{Slide: p.Slide}); err == nil {
				p.URL = served
			}
			if bridged, err := server.URL(grant.ArtifactID, preview.URLOptions{Slide: p.Slide, Bridge: true}); err == nil {
				p.BridgeURL = bridged
			}
		}
	}

	if nodeID != "" {
		if _, err := s.store.GetNode(ctx, artifact.ID, artifact.CurrentVersion, nodeID); err != nil {
			return Presentation{}, fmt.Errorf("design: node %s is not in the index of version %d; run a render first", nodeID, artifact.CurrentVersion)
		}
		p.Selection = SelectionURI(nodeID)
	}
	return p, nil
}

// SelectionURI formats the selection protocol every surface speaks.
func SelectionURI(nodeID string) string { return "design://" + nodeID }

// ParseSelectionURI extracts the node id from a selection reference.
func ParseSelectionURI(uri string) (string, bool) {
	const prefix = "design://"
	if !strings.HasPrefix(uri, prefix) {
		return "", false
	}
	id := strings.TrimPrefix(uri, prefix)
	if id == "" {
		return "", false
	}
	return id, true
}

// WriteWorkspaceFile writes generated bytes to a working-directory-relative
// path, refusing to escape the project. It backs image generation, whose output
// belongs next to the artifact that uses it rather than in a cache.
func (s *Service) WriteWorkspaceFile(rel string, data []byte) (string, error) {
	cleaned := filepath.Clean(filepath.FromSlash(rel))
	if filepath.IsAbs(cleaned) || cleaned == ".." || hasParentPrefix(cleaned) {
		return "", fmt.Errorf("design: %q escapes the working directory", rel)
	}
	root, err := filepath.Abs(s.layout.WorkingDir)
	if err != nil {
		return "", err
	}
	target := filepath.Join(root, cleaned)
	if target != root && !strings.HasPrefix(target, root+string(filepath.Separator)) {
		return "", fmt.Errorf("design: %q escapes the working directory", rel)
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return "", fmt.Errorf("design: create dir for %s: %w", rel, err)
	}
	if err := os.WriteFile(target, data, 0o644); err != nil {
		return "", fmt.Errorf("design: write %s: %w", rel, err)
	}
	return filepath.ToSlash(cleaned), nil
}
