// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createFileStmt, err = db.PrepareContext(ctx, createFile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFile: %w", err)
	}
	if q.createGoalStmt, err = db.PrepareContext(ctx, createGoal); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGoal: %w", err)
	}
	if q.createMessageStmt, err = db.PrepareContext(ctx, createMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateMessage: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.deleteFileStmt, err = db.PrepareContext(ctx, deleteFile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFile: %w", err)
	}
	if q.deleteGoalsBySessionStmt, err = db.PrepareContext(ctx, deleteGoalsBySession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteGoalsBySession: %w", err)
	}
	if q.deleteMessageStmt, err = db.PrepareContext(ctx, deleteMessage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteMessage: %w", err)
	}
	if q.deleteSessionStmt, err = db.PrepareContext(ctx, deleteSession); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSession: %w", err)
	}
	if q.deleteSessionFilesStmt, err = db.PrepareContext(ctx, deleteSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionFiles: %w", err)
	}
	if q.deleteSessionMessagesStmt, err = db.PrepareContext(ctx, deleteSessionMessages); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionMessages: %w", err)
	}
	if q.getFileStmt, err = db.PrepareContext(ctx, getFile); err != nil {
		return nil, fmt.Errorf("error preparing query GetFile: %w", err)
	}
	if q.getFileByPathAndSessionStmt, err = db.PrepareContext(ctx, getFileByPathAndSession); err != nil {
		return nil, fmt.Errorf("error preparing query GetFileByPathAndSession: %w", err)
	}
	if q.getActiveGoalStmt, err = db.PrepareContext(ctx, getActiveGoal); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveGoal: %w", err)
	}
	if q.getGoalBySessionStmt, err = db.PrepareContext(ctx, getGoalBySession); err != nil {
		return nil, fmt.Errorf("error preparing query GetGoalBySession: %w", err)
	}
	if q.getMessageStmt, err = db.PrepareContext(ctx, getMessage); err != nil {
		return nil, fmt.Errorf("error preparing query GetMessage: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.listFilesByPathStmt, err = db.PrepareContext(ctx, listFilesByPath); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesByPath: %w", err)
	}
	if q.listFilesBySessionStmt, err = db.PrepareContext(ctx, listFilesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListFilesBySession: %w", err)
	}
	if q.listLatestSessionFilesStmt, err = db.PrepareContext(ctx, listLatestSessionFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListLatestSessionFiles: %w", err)
	}
	if q.listMessagesBySessionStmt, err = db.PrepareContext(ctx, listMessagesBySession); err != nil {
		return nil, fmt.Errorf("error preparing query ListMessagesBySession: %w", err)
	}
	if q.listNewFilesStmt, err = db.PrepareContext(ctx, listNewFiles); err != nil {
		return nil, fmt.Errorf("error preparing query ListNewFiles: %w", err)
	}
	if q.updateSessionScoreStmt, err = db.PrepareContext(ctx, updateSessionScore); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionScore: %w", err)
	}
	if q.updateSessionScoreJudgeStmt, err = db.PrepareContext(ctx, updateSessionScoreJudge); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSessionScoreJudge: %w", err)
	}
	if q.getJudgeUsageSinceStmt, err = db.PrepareContext(ctx, getJudgeUsageSince); err != nil {
		return nil, fmt.Errorf("error preparing query GetJudgeUsageSince: %w", err)
	}
	if q.insertSessionTemplateSelectionStmt, err = db.PrepareContext(ctx, insertSessionTemplateSelection); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSessionTemplateSelection: %w", err)
	}
	if q.getSessionTemplateSelectionStmt, err = db.PrepareContext(ctx, getSessionTemplateSelection); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionTemplateSelection: %w", err)
	}
	if q.listVariantSelectionCountsStmt, err = db.PrepareContext(ctx, listVariantSelectionCounts); err != nil {
		return nil, fmt.Errorf("error preparing query ListVariantSelectionCounts: %w", err)
	}
	if q.listVariantStatsBySectionStmt, err = db.PrepareContext(ctx, listVariantStatsBySection); err != nil {
		return nil, fmt.Errorf("error preparing query ListVariantStatsBySection: %w", err)
	}
	if q.listAllVariantStatsStmt, err = db.PrepareContext(ctx, listAllVariantStats); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllVariantStats: %w", err)
	}
	if q.applySessionRewardToVariantStatsStmt, err = db.PrepareContext(ctx, applySessionRewardToVariantStats); err != nil {
		return nil, fmt.Errorf("error preparing query ApplySessionRewardToVariantStats: %w", err)
	}
	if q.applyRewardDeltaToVariantStatsStmt, err = db.PrepareContext(ctx, applyRewardDeltaToVariantStats); err != nil {
		return nil, fmt.Errorf("error preparing query ApplyRewardDeltaToVariantStats: %w", err)
	}
	if q.getSessionsTokenBaselineStmt, err = db.PrepareContext(ctx, getSessionsTokenBaseline); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionsTokenBaseline: %w", err)
	}
	if q.insertSessionFeedbackEventStmt, err = db.PrepareContext(ctx, insertSessionFeedbackEvent); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSessionFeedbackEvent: %w", err)
	}
	if q.getLatestSessionFeedbackStmt, err = db.PrepareContext(ctx, getLatestSessionFeedback); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestSessionFeedback: %w", err)
	}
	if q.listUnscoredSessionsStmt, err = db.PrepareContext(ctx, listUnscoredSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListUnscoredSessions: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.updateFileStmt, err = db.PrepareContext(ctx, updateFile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateFile: %w", err)
	}
	if q.updateGoalProgressStmt, err = db.PrepareContext(ctx, updateGoalProgress); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGoalProgress: %w", err)
	}
	if q.updateGoalStatusStmt, err = db.PrepareContext(ctx, updateGoalStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateGoalStatus: %w", err)
	}
	if q.updateMessageStmt, err = db.PrepareContext(ctx, updateMessage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateMessage: %w", err)
	}
	if q.updateSessionStmt, err = db.PrepareContext(ctx, updateSession); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSession: %w", err)
	}
	if q.insertSessionScoreStmt, err = db.PrepareContext(ctx, insertSessionScore); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSessionScore: %w", err)
	}
	if q.getSessionScoreStmt, err = db.PrepareContext(ctx, getSessionScore); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionScore: %w", err)
	}
	if q.countSessionScoresStmt, err = db.PrepareContext(ctx, countSessionScores); err != nil {
		return nil, fmt.Errorf("error preparing query CountSessionScores: %w", err)
	}
	if q.listSessionScoresStmt, err = db.PrepareContext(ctx, listSessionScores); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessionScores: %w", err)
	}
	if q.insertSkillStmt, err = db.PrepareContext(ctx, insertSkill); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSkill: %w", err)
	}
	if q.listActiveSkillsByTypeStmt, err = db.PrepareContext(ctx, listActiveSkillsByType); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveSkillsByType: %w", err)
	}
	if q.listAllActiveSkillsStmt, err = db.PrepareContext(ctx, listAllActiveSkills); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllActiveSkills: %w", err)
	}
	if q.countActiveSkillsStmt, err = db.PrepareContext(ctx, countActiveSkills); err != nil {
		return nil, fmt.Errorf("error preparing query CountActiveSkills: %w", err)
	}
	if q.incrementSkillUsageStmt, err = db.PrepareContext(ctx, incrementSkillUsage); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementSkillUsage: %w", err)
	}
	if q.getEvaluatorStatsStmt, err = db.PrepareContext(ctx, getEvaluatorStats); err != nil {
		return nil, fmt.Errorf("error preparing query GetEvaluatorStats: %w", err)
	}
	if q.createProjectStmt, err = db.PrepareContext(ctx, createProject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProject: %w", err)
	}
	if q.getProjectStmt, err = db.PrepareContext(ctx, getProject); err != nil {
		return nil, fmt.Errorf("error preparing query GetProject: %w", err)
	}
	if q.getProjectByPathStmt, err = db.PrepareContext(ctx, getProjectByPath); err != nil {
		return nil, fmt.Errorf("error preparing query GetProjectByPath: %w", err)
	}
	if q.listProjectsStmt, err = db.PrepareContext(ctx, listProjects); err != nil {
		return nil, fmt.Errorf("error preparing query ListProjects: %w", err)
	}
	if q.updateProjectStatusStmt, err = db.PrepareContext(ctx, updateProjectStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProjectStatus: %w", err)
	}
	if q.updateProjectWebRuntimeStmt, err = db.PrepareContext(ctx, updateProjectWebRuntime); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProjectWebRuntime: %w", err)
	}
	if q.updateProjectLastOpenedStmt, err = db.PrepareContext(ctx, updateProjectLastOpened); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProjectLastOpened: %w", err)
	}
	if q.markProjectInitializedStmt, err = db.PrepareContext(ctx, markProjectInitialized); err != nil {
		return nil, fmt.Errorf("error preparing query MarkProjectInitialized: %w", err)
	}
	if q.deleteProjectStmt, err = db.PrepareContext(ctx, deleteProject); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProject: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createFileStmt != nil {
		if cerr := q.createFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFileStmt: %w", cerr)
		}
	}
	if q.createGoalStmt != nil {
		if cerr := q.createGoalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGoalStmt: %w", cerr)
		}
	}
	if q.createMessageStmt != nil {
		if cerr := q.createMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createMessageStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.deleteFileStmt != nil {
		if cerr := q.deleteFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFileStmt: %w", cerr)
		}
	}
	if q.deleteGoalsBySessionStmt != nil {
		if cerr := q.deleteGoalsBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteGoalsBySessionStmt: %w", cerr)
		}
	}
	if q.deleteMessageStmt != nil {
		if cerr := q.deleteMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteMessageStmt: %w", cerr)
		}
	}
	if q.deleteSessionStmt != nil {
		if cerr := q.deleteSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionStmt: %w", cerr)
		}
	}
	if q.deleteSessionFilesStmt != nil {
		if cerr := q.deleteSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionFilesStmt: %w", cerr)
		}
	}
	if q.deleteSessionMessagesStmt != nil {
		if cerr := q.deleteSessionMessagesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionMessagesStmt: %w", cerr)
		}
	}
	if q.getFileStmt != nil {
		if cerr := q.getFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileStmt: %w", cerr)
		}
	}
	if q.getFileByPathAndSessionStmt != nil {
		if cerr := q.getFileByPathAndSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFileByPathAndSessionStmt: %w", cerr)
		}
	}
	if q.getActiveGoalStmt != nil {
		if cerr := q.getActiveGoalStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveGoalStmt: %w", cerr)
		}
	}
	if q.getGoalBySessionStmt != nil {
		if cerr := q.getGoalBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getGoalBySessionStmt: %w", cerr)
		}
	}
	if q.getMessageStmt != nil {
		if cerr := q.getMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMessageStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.listFilesByPathStmt != nil {
		if cerr := q.listFilesByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesByPathStmt: %w", cerr)
		}
	}
	if q.listFilesBySessionStmt != nil {
		if cerr := q.listFilesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFilesBySessionStmt: %w", cerr)
		}
	}
	if q.listLatestSessionFilesStmt != nil {
		if cerr := q.listLatestSessionFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLatestSessionFilesStmt: %w", cerr)
		}
	}
	if q.listMessagesBySessionStmt != nil {
		if cerr := q.listMessagesBySessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMessagesBySessionStmt: %w", cerr)
		}
	}
	if q.listNewFilesStmt != nil {
		if cerr := q.listNewFilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNewFilesStmt: %w", cerr)
		}
	}
	if q.updateSessionScoreStmt != nil {
		if cerr := q.updateSessionScoreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionScoreStmt: %w", cerr)
		}
	}
	if q.updateSessionScoreJudgeStmt != nil {
		if cerr := q.updateSessionScoreJudgeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionScoreJudgeStmt: %w", cerr)
		}
	}
	if q.getJudgeUsageSinceStmt != nil {
		if cerr := q.getJudgeUsageSinceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getJudgeUsageSinceStmt: %w", cerr)
		}
	}
	if q.insertSessionTemplateSelectionStmt != nil {
		if cerr := q.insertSessionTemplateSelectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSessionTemplateSelectionStmt: %w", cerr)
		}
	}
	if q.getSessionTemplateSelectionStmt != nil {
		if cerr := q.getSessionTemplateSelectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionTemplateSelectionStmt: %w", cerr)
		}
	}
	if q.listVariantSelectionCountsStmt != nil {
		if cerr := q.listVariantSelectionCountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVariantSelectionCountsStmt: %w", cerr)
		}
	}
	if q.listVariantStatsBySectionStmt != nil {
		if cerr := q.listVariantStatsBySectionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVariantStatsBySectionStmt: %w", cerr)
		}
	}
	if q.listAllVariantStatsStmt != nil {
		if cerr := q.listAllVariantStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllVariantStatsStmt: %w", cerr)
		}
	}
	if q.applySessionRewardToVariantStatsStmt != nil {
		if cerr := q.applySessionRewardToVariantStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing applySessionRewardToVariantStatsStmt: %w", cerr)
		}
	}
	if q.applyRewardDeltaToVariantStatsStmt != nil {
		if cerr := q.applyRewardDeltaToVariantStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing applyRewardDeltaToVariantStatsStmt: %w", cerr)
		}
	}
	if q.getSessionsTokenBaselineStmt != nil {
		if cerr := q.getSessionsTokenBaselineStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionsTokenBaselineStmt: %w", cerr)
		}
	}
	if q.insertSessionFeedbackEventStmt != nil {
		if cerr := q.insertSessionFeedbackEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSessionFeedbackEventStmt: %w", cerr)
		}
	}
	if q.getLatestSessionFeedbackStmt != nil {
		if cerr := q.getLatestSessionFeedbackStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestSessionFeedbackStmt: %w", cerr)
		}
	}
	if q.listUnscoredSessionsStmt != nil {
		if cerr := q.listUnscoredSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUnscoredSessionsStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.updateFileStmt != nil {
		if cerr := q.updateFileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateFileStmt: %w", cerr)
		}
	}
	if q.updateGoalProgressStmt != nil {
		if cerr := q.updateGoalProgressStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGoalProgressStmt: %w", cerr)
		}
	}
	if q.updateGoalStatusStmt != nil {
		if cerr := q.updateGoalStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateGoalStatusStmt: %w", cerr)
		}
	}
	if q.updateMessageStmt != nil {
		if cerr := q.updateMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateMessageStmt: %w", cerr)
		}
	}
	if q.updateSessionStmt != nil {
		if cerr := q.updateSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSessionStmt: %w", cerr)
		}
	}
	if q.insertSessionScoreStmt != nil {
		if cerr := q.insertSessionScoreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSessionScoreStmt: %w", cerr)
		}
	}
	if q.getSessionScoreStmt != nil {
		if cerr := q.getSessionScoreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionScoreStmt: %w", cerr)
		}
	}
	if q.countSessionScoresStmt != nil {
		if cerr := q.countSessionScoresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countSessionScoresStmt: %w", cerr)
		}
	}
	if q.listSessionScoresStmt != nil {
		if cerr := q.listSessionScoresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionScoresStmt: %w", cerr)
		}
	}
	if q.insertSkillStmt != nil {
		if cerr := q.insertSkillStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSkillStmt: %w", cerr)
		}
	}
	if q.listActiveSkillsByTypeStmt != nil {
		if cerr := q.listActiveSkillsByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveSkillsByTypeStmt: %w", cerr)
		}
	}
	if q.listAllActiveSkillsStmt != nil {
		if cerr := q.listAllActiveSkillsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllActiveSkillsStmt: %w", cerr)
		}
	}
	if q.countActiveSkillsStmt != nil {
		if cerr := q.countActiveSkillsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countActiveSkillsStmt: %w", cerr)
		}
	}
	if q.incrementSkillUsageStmt != nil {
		if cerr := q.incrementSkillUsageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementSkillUsageStmt: %w", cerr)
		}
	}
	if q.getEvaluatorStatsStmt != nil {
		if cerr := q.getEvaluatorStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEvaluatorStatsStmt: %w", cerr)
		}
	}
	if q.createProjectStmt != nil {
		if cerr := q.createProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProjectStmt: %w", cerr)
		}
	}
	if q.getProjectStmt != nil {
		if cerr := q.getProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectStmt: %w", cerr)
		}
	}
	if q.getProjectByPathStmt != nil {
		if cerr := q.getProjectByPathStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProjectByPathStmt: %w", cerr)
		}
	}
	if q.listProjectsStmt != nil {
		if cerr := q.listProjectsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProjectsStmt: %w", cerr)
		}
	}
	if q.updateProjectStatusStmt != nil {
		if cerr := q.updateProjectStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProjectStatusStmt: %w", cerr)
		}
	}
	if q.updateProjectWebRuntimeStmt != nil {
		if cerr := q.updateProjectWebRuntimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProjectWebRuntimeStmt: %w", cerr)
		}
	}
	if q.updateProjectLastOpenedStmt != nil {
		if cerr := q.updateProjectLastOpenedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProjectLastOpenedStmt: %w", cerr)
		}
	}
	if q.markProjectInitializedStmt != nil {
		if cerr := q.markProjectInitializedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markProjectInitializedStmt: %w", cerr)
		}
	}
	if q.deleteProjectStmt != nil {
		if cerr := q.deleteProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProjectStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	createFileStmt                       *sql.Stmt
	createGoalStmt                       *sql.Stmt
	createMessageStmt                    *sql.Stmt
	createSessionStmt                    *sql.Stmt
	deleteFileStmt                       *sql.Stmt
	deleteGoalsBySessionStmt             *sql.Stmt
	deleteMessageStmt                    *sql.Stmt
	deleteSessionStmt                    *sql.Stmt
	deleteSessionFilesStmt               *sql.Stmt
	deleteSessionMessagesStmt            *sql.Stmt
	getFileStmt                          *sql.Stmt
	getFileByPathAndSessionStmt          *sql.Stmt
	getActiveGoalStmt                    *sql.Stmt
	getGoalBySessionStmt                 *sql.Stmt
	getMessageStmt                       *sql.Stmt
	getSessionByIDStmt                   *sql.Stmt
	listFilesByPathStmt                  *sql.Stmt
	listFilesBySessionStmt               *sql.Stmt
	listLatestSessionFilesStmt           *sql.Stmt
	listMessagesBySessionStmt            *sql.Stmt
	listNewFilesStmt                     *sql.Stmt
	listSessionsStmt                     *sql.Stmt
	listUnscoredSessionsStmt             *sql.Stmt
	updateSessionScoreStmt               *sql.Stmt
	updateSessionScoreJudgeStmt          *sql.Stmt
	getJudgeUsageSinceStmt               *sql.Stmt
	insertSessionTemplateSelectionStmt   *sql.Stmt
	getSessionTemplateSelectionStmt      *sql.Stmt
	listVariantSelectionCountsStmt       *sql.Stmt
	listVariantStatsBySectionStmt        *sql.Stmt
	listAllVariantStatsStmt              *sql.Stmt
	applySessionRewardToVariantStatsStmt *sql.Stmt
	applyRewardDeltaToVariantStatsStmt   *sql.Stmt
	getSessionsTokenBaselineStmt         *sql.Stmt
	insertSessionFeedbackEventStmt       *sql.Stmt
	getLatestSessionFeedbackStmt         *sql.Stmt
	updateFileStmt                       *sql.Stmt
	updateGoalProgressStmt               *sql.Stmt
	updateGoalStatusStmt                 *sql.Stmt
	updateMessageStmt                    *sql.Stmt
	updateSessionStmt                    *sql.Stmt
	insertSessionScoreStmt               *sql.Stmt
	getSessionScoreStmt                  *sql.Stmt
	countSessionScoresStmt               *sql.Stmt
	listSessionScoresStmt                *sql.Stmt
	insertSkillStmt                      *sql.Stmt
	listActiveSkillsByTypeStmt           *sql.Stmt
	listAllActiveSkillsStmt              *sql.Stmt
	countActiveSkillsStmt                *sql.Stmt
	incrementSkillUsageStmt              *sql.Stmt
	getEvaluatorStatsStmt                *sql.Stmt
	createProjectStmt                    *sql.Stmt
	getProjectStmt                       *sql.Stmt
	getProjectByPathStmt                 *sql.Stmt
	listProjectsStmt                     *sql.Stmt
	updateProjectStatusStmt              *sql.Stmt
	updateProjectWebRuntimeStmt          *sql.Stmt
	updateProjectLastOpenedStmt          *sql.Stmt
	markProjectInitializedStmt           *sql.Stmt
	deleteProjectStmt                    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		createFileStmt:                       q.createFileStmt,
		createGoalStmt:                       q.createGoalStmt,
		createMessageStmt:                    q.createMessageStmt,
		createSessionStmt:                    q.createSessionStmt,
		deleteFileStmt:                       q.deleteFileStmt,
		deleteGoalsBySessionStmt:             q.deleteGoalsBySessionStmt,
		deleteMessageStmt:                    q.deleteMessageStmt,
		deleteSessionStmt:                    q.deleteSessionStmt,
		deleteSessionFilesStmt:               q.deleteSessionFilesStmt,
		deleteSessionMessagesStmt:            q.deleteSessionMessagesStmt,
		getFileStmt:                          q.getFileStmt,
		getFileByPathAndSessionStmt:          q.getFileByPathAndSessionStmt,
		getActiveGoalStmt:                    q.getActiveGoalStmt,
		getGoalBySessionStmt:                 q.getGoalBySessionStmt,
		getMessageStmt:                       q.getMessageStmt,
		getSessionByIDStmt:                   q.getSessionByIDStmt,
		listFilesByPathStmt:                  q.listFilesByPathStmt,
		listFilesBySessionStmt:               q.listFilesBySessionStmt,
		listLatestSessionFilesStmt:           q.listLatestSessionFilesStmt,
		listMessagesBySessionStmt:            q.listMessagesBySessionStmt,
		listNewFilesStmt:                     q.listNewFilesStmt,
		listSessionsStmt:                     q.listSessionsStmt,
		listUnscoredSessionsStmt:             q.listUnscoredSessionsStmt,
		updateSessionScoreStmt:               q.updateSessionScoreStmt,
		updateSessionScoreJudgeStmt:          q.updateSessionScoreJudgeStmt,
		getJudgeUsageSinceStmt:               q.getJudgeUsageSinceStmt,
		insertSessionTemplateSelectionStmt:   q.insertSessionTemplateSelectionStmt,
		getSessionTemplateSelectionStmt:      q.getSessionTemplateSelectionStmt,
		listVariantSelectionCountsStmt:       q.listVariantSelectionCountsStmt,
		listVariantStatsBySectionStmt:        q.listVariantStatsBySectionStmt,
		listAllVariantStatsStmt:              q.listAllVariantStatsStmt,
		applySessionRewardToVariantStatsStmt: q.applySessionRewardToVariantStatsStmt,
		applyRewardDeltaToVariantStatsStmt:   q.applyRewardDeltaToVariantStatsStmt,
		getSessionsTokenBaselineStmt:         q.getSessionsTokenBaselineStmt,
		insertSessionFeedbackEventStmt:       q.insertSessionFeedbackEventStmt,
		getLatestSessionFeedbackStmt:         q.getLatestSessionFeedbackStmt,
		updateFileStmt:                       q.updateFileStmt,
		updateGoalProgressStmt:               q.updateGoalProgressStmt,
		updateGoalStatusStmt:                 q.updateGoalStatusStmt,
		updateMessageStmt:                    q.updateMessageStmt,
		updateSessionStmt:                    q.updateSessionStmt,
		insertSessionScoreStmt:               q.insertSessionScoreStmt,
		getSessionScoreStmt:                  q.getSessionScoreStmt,
		countSessionScoresStmt:               q.countSessionScoresStmt,
		listSessionScoresStmt:                q.listSessionScoresStmt,
		insertSkillStmt:                      q.insertSkillStmt,
		listActiveSkillsByTypeStmt:           q.listActiveSkillsByTypeStmt,
		listAllActiveSkillsStmt:              q.listAllActiveSkillsStmt,
		countActiveSkillsStmt:                q.countActiveSkillsStmt,
		incrementSkillUsageStmt:              q.incrementSkillUsageStmt,
		getEvaluatorStatsStmt:                q.getEvaluatorStatsStmt,
		createProjectStmt:                    q.createProjectStmt,
		getProjectStmt:                       q.getProjectStmt,
		getProjectByPathStmt:                 q.getProjectByPathStmt,
		listProjectsStmt:                     q.listProjectsStmt,
		updateProjectStatusStmt:              q.updateProjectStatusStmt,
		updateProjectWebRuntimeStmt:          q.updateProjectWebRuntimeStmt,
		updateProjectLastOpenedStmt:          q.updateProjectLastOpenedStmt,
		markProjectInitializedStmt:           q.markProjectInitializedStmt,
		deleteProjectStmt:                    q.deleteProjectStmt,
	}
}
