// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    name,
    path,
    status,
    initialized,
    acp_pid,
    acp_port,
    last_opened,
    created_at,
    updated_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now')
) RETURNING id, name, path, status, initialized, acp_pid, acp_port, last_opened, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Path        string        `json:"path"`
	Status      string        `json:"status"`
	Initialized int64         `json:"initialized"`
	AcpPid      sql.NullInt64 `json:"acp_pid"`
	AcpPort     sql.NullInt64 `json:"acp_port"`
	LastOpened  sql.NullInt64 `json:"last_opened"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.createProjectStmt, createProject,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Status,
		arg.Initialized,
		arg.AcpPid,
		arg.AcpPort,
		arg.LastOpened,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Status,
		&i.Initialized,
		&i.AcpPid,
		&i.AcpPort,
		&i.LastOpened,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, path, status, initialized, acp_pid, acp_port, last_opened, created_at, updated_at
FROM projects
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.queryRow(ctx, q.getProjectStmt, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Status,
		&i.Initialized,
		&i.AcpPid,
		&i.AcpPort,
		&i.LastOpened,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByPath = `-- name: GetProjectByPath :one
SELECT id, name, path, status, initialized, acp_pid, acp_port, last_opened, created_at, updated_at
FROM projects
WHERE path = ? LIMIT 1
`

func (q *Queries) GetProjectByPath(ctx context.Context, path string) (Project, error) {
	row := q.queryRow(ctx, q.getProjectByPathStmt, getProjectByPath, path)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Status,
		&i.Initialized,
		&i.AcpPid,
		&i.AcpPort,
		&i.LastOpened,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, path, status, initialized, acp_pid, acp_port, last_opened, created_at, updated_at
FROM projects
ORDER BY last_opened DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsStmt, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Status,
			&i.Initialized,
			&i.AcpPid,
			&i.AcpPort,
			&i.LastOpened,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectStatus = `-- name: UpdateProjectStatus :exec
UPDATE projects
SET
    status     = ?,
    acp_pid    = ?,
    acp_port   = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateProjectStatusParams struct {
	Status  string        `json:"status"`
	AcpPid  sql.NullInt64 `json:"acp_pid"`
	AcpPort sql.NullInt64 `json:"acp_port"`
	ID      string        `json:"id"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error {
	_, err := q.exec(ctx, q.updateProjectStatusStmt, updateProjectStatus,
		arg.Status,
		arg.AcpPid,
		arg.AcpPort,
		arg.ID,
	)
	return err
}

const updateProjectLastOpened = `-- name: UpdateProjectLastOpened :exec
UPDATE projects
SET
    last_opened = ?,
    updated_at  = strftime('%s', 'now')
WHERE id = ?
`

type UpdateProjectLastOpenedParams struct {
	LastOpened sql.NullInt64 `json:"last_opened"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateProjectLastOpened(ctx context.Context, arg UpdateProjectLastOpenedParams) error {
	_, err := q.exec(ctx, q.updateProjectLastOpenedStmt, updateProjectLastOpened,
		arg.LastOpened,
		arg.ID,
	)
	return err
}

const markProjectInitialized = `-- name: MarkProjectInitialized :exec
UPDATE projects
SET
    initialized = 1,
    updated_at  = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) MarkProjectInitialized(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.markProjectInitializedStmt, markProjectInitialized, id)
	return err
}

const updateProjectName = `-- name: UpdateProjectName :exec
UPDATE projects
SET
    name       = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) UpdateProjectName(ctx context.Context, id, name string) error {
	_, err := q.exec(ctx, nil, updateProjectName, name, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteProjectStmt, deleteProject, id)
	return err
}
