// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (SessionGoal, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteGoalsBySession(ctx context.Context, sessionID string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetActiveGoal(ctx context.Context, sessionID string) (SessionGoal, error)
	GetGoalBySession(ctx context.Context, sessionID string) (SessionGoal, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessions(ctx context.Context) ([]Session, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateGoalProgress(ctx context.Context, arg UpdateGoalProgressParams) (SessionGoal, error)
	UpdateGoalStatus(ctx context.Context, arg UpdateGoalStatusParams) (SessionGoal, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	// Self-improvement queries
	InsertPromptTemplate(ctx context.Context, arg InsertPromptTemplateParams) (PromptTemplate, error)
	GetPromptTemplate(ctx context.Context, id string) (PromptTemplate, error)
	ListActiveTemplatesBySection(ctx context.Context, section string) ([]ListActiveTemplatesBySectionRow, error)
	CountPromptTemplates(ctx context.Context) (int64, error)
	InsertSessionScore(ctx context.Context, arg InsertSessionScoreParams) (SessionScore, error)
	ListUnscoredSessions(ctx context.Context, arg ListUnscoredSessionsParams) ([]string, error)
	GetSessionScore(ctx context.Context, sessionID string) (SessionScore, error)
	UpdateSessionScore(ctx context.Context, arg UpdateSessionScoreParams) (SessionScore, error)
	UpdateSessionScoreJudge(ctx context.Context, arg UpdateSessionScoreJudgeParams) error
	GetJudgeUsageSince(ctx context.Context, createdAt int64) (GetJudgeUsageSinceRow, error)
	InsertSessionTemplateSelection(ctx context.Context, arg InsertSessionTemplateSelectionParams) error
	GetSessionTemplateSelection(ctx context.Context, arg GetSessionTemplateSelectionParams) (string, error)
	ListVariantSelectionCounts(ctx context.Context, section string) ([]ListVariantSelectionCountsRow, error)
	ListVariantStatsBySection(ctx context.Context, section string) ([]PromptVariantStat, error)
	ListAllVariantStats(ctx context.Context) ([]PromptVariantStat, error)
	ApplySessionRewardToVariantStats(ctx context.Context, arg ApplySessionRewardToVariantStatsParams) error
	ApplyRewardDeltaToVariantStats(ctx context.Context, arg ApplyRewardDeltaToVariantStatsParams) error
	GetSessionsTokenBaseline(ctx context.Context, arg GetSessionsTokenBaselineParams) (float64, error)
	InsertSessionFeedbackEvent(ctx context.Context, arg InsertSessionFeedbackEventParams) (int64, error)
	GetLatestSessionFeedback(ctx context.Context, subject string) (string, error)
	CountSessionScores(ctx context.Context) (int64, error)
	ListSessionScores(ctx context.Context, limit int64) ([]SessionScore, error)
	GetTokenBaseline(ctx context.Context, limit int64) (float64, error)
	GetUCBStats(ctx context.Context, templateID string) (PromptUcbStat, error)
	InsertSkill(ctx context.Context, arg InsertSkillParams) (SkillLibrary, error)
	ListActiveSkillsByType(ctx context.Context, arg ListActiveSkillsByTypeParams) ([]SkillLibrary, error)
	ListAllActiveSkills(ctx context.Context) ([]SkillLibrary, error)
	CountActiveSkills(ctx context.Context) (int64, error)
	DeactivateLowestSkill(ctx context.Context) error
	// DeactivateUnderperformingSkills deactivates skills that have low success rate and
	// high usage, indicating they do not improve outcomes despite being frequently selected.
	DeactivateUnderperformingSkills(ctx context.Context) error
	IncrementSkillUsage(ctx context.Context, id string) error
	// Reviewable learned skills (files are the source of truth, the table mirrors them).
	UpsertSkillMirror(ctx context.Context, arg UpsertSkillMirrorParams) error
	SetSkillMirrorState(ctx context.Context, arg SetSkillMirrorStateParams) error
	ListAllSkills(ctx context.Context) ([]SkillLibrary, error)
	GetSkill(ctx context.Context, id string) (SkillLibrary, error)
	InsertSessionSkillInjection(ctx context.Context, arg InsertSessionSkillInjectionParams) error
	CountSessionSkillInjections(ctx context.Context, sessionID string) (int64, error)
	ListSessionInjectedSkills(ctx context.Context, sessionID string) ([]SkillLibrary, error)
	ApplySessionRewardToSkillStats(ctx context.Context, arg ApplySessionRewardToSkillStatsParams) error
	ApplyRewardDeltaToSkillStats(ctx context.Context, arg ApplyRewardDeltaToSkillStatsParams) error
	ListUCBRanking(ctx context.Context) ([]ListUCBRankingRow, error)
	GetEvaluatorStats(ctx context.Context) (GetEvaluatorStatsRow, error)
	// Project queries
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectByPath(ctx context.Context, path string) (Project, error)
	ListProjects(ctx context.Context) ([]Project, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error
	UpdateProjectLastOpened(ctx context.Context, arg UpdateProjectLastOpenedParams) error
	MarkProjectInitialized(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
	// ACP session state
	GetSessionACPState(ctx context.Context, id string) (sql.NullString, error)
	UpdateSessionACPState(ctx context.Context, arg UpdateSessionACPStateParams) error
}

var _ Querier = (*Queries)(nil)
