// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListSessions(ctx context.Context) ([]Session, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	// Self-improvement queries
	InsertPromptTemplate(ctx context.Context, arg InsertPromptTemplateParams) (PromptTemplate, error)
	GetPromptTemplate(ctx context.Context, id string) (PromptTemplate, error)
	ListActiveTemplatesBySection(ctx context.Context, section string) ([]ListActiveTemplatesBySectionRow, error)
	CountPromptTemplates(ctx context.Context) (int64, error)
	InsertSessionScore(ctx context.Context, arg InsertSessionScoreParams) (SessionScore, error)
	GetSessionScore(ctx context.Context, sessionID string) (SessionScore, error)
	CountSessionScores(ctx context.Context) (int64, error)
	ListSessionScores(ctx context.Context, limit int64) ([]SessionScore, error)
	GetTokenBaseline(ctx context.Context, limit int64) (float64, error)
	GetUCBStats(ctx context.Context, templateID string) (PromptUcbStat, error)
	InsertSkill(ctx context.Context, arg InsertSkillParams) (SkillLibrary, error)
	ListActiveSkillsByType(ctx context.Context, arg ListActiveSkillsByTypeParams) ([]SkillLibrary, error)
	ListAllActiveSkills(ctx context.Context) ([]SkillLibrary, error)
	CountActiveSkills(ctx context.Context) (int64, error)
	DeactivateLowestSkill(ctx context.Context) error
	IncrementSkillUsage(ctx context.Context, id string) error
	ListUCBRanking(ctx context.Context) ([]ListUCBRankingRow, error)
	GetEvaluatorStats(ctx context.Context) (GetEvaluatorStatsRow, error)
	// Project queries
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectByPath(ctx context.Context, path string) (Project, error)
	ListProjects(ctx context.Context) ([]Project, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error
	UpdateProjectLastOpened(ctx context.Context, arg UpdateProjectLastOpenedParams) error
	MarkProjectInitialized(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
