// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: self_improvement.sql

package db

import (
	"context"
	"database/sql"
)

const insertSessionScore = `-- name: InsertSessionScore :one
INSERT INTO session_scores (
    id, session_id, template_id, reward, success_score, efficiency_score,
    judge_analysis, judge_model, prompt_tokens, completion_tokens,
    message_count, user_corrections, components, judge_prompt_tokens, judge_completion_tokens,
    evaluated_at, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, session_id, template_id, reward, success_score, efficiency_score, judge_analysis, judge_model, prompt_tokens, completion_tokens, message_count, user_corrections, evaluated_at, created_at, components, judge_prompt_tokens, judge_completion_tokens
`

type InsertSessionScoreParams struct {
	ID                    string         `json:"id"`
	SessionID             string         `json:"session_id"`
	TemplateID            sql.NullString `json:"template_id"`
	Reward                float64        `json:"reward"`
	SuccessScore          float64        `json:"success_score"`
	EfficiencyScore       float64        `json:"efficiency_score"`
	JudgeAnalysis         sql.NullString `json:"judge_analysis"`
	JudgeModel            sql.NullString `json:"judge_model"`
	PromptTokens          int64          `json:"prompt_tokens"`
	CompletionTokens      int64          `json:"completion_tokens"`
	MessageCount          int64          `json:"message_count"`
	UserCorrections       int64          `json:"user_corrections"`
	Components            string         `json:"components"`
	JudgePromptTokens     int64          `json:"judge_prompt_tokens"`
	JudgeCompletionTokens int64          `json:"judge_completion_tokens"`
}

func (q *Queries) InsertSessionScore(ctx context.Context, arg InsertSessionScoreParams) (SessionScore, error) {
	row := q.queryRow(ctx, q.insertSessionScoreStmt, insertSessionScore,
		arg.ID,
		arg.SessionID,
		arg.TemplateID,
		arg.Reward,
		arg.SuccessScore,
		arg.EfficiencyScore,
		arg.JudgeAnalysis,
		arg.JudgeModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.MessageCount,
		arg.UserCorrections,
		arg.Components,
		arg.JudgePromptTokens,
		arg.JudgeCompletionTokens,
	)
	var i SessionScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TemplateID,
		&i.Reward,
		&i.SuccessScore,
		&i.EfficiencyScore,
		&i.JudgeAnalysis,
		&i.JudgeModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.MessageCount,
		&i.UserCorrections,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.Components,
		&i.JudgePromptTokens,
		&i.JudgeCompletionTokens,
	)
	return i, err
}

const getSessionScore = `-- name: GetSessionScore :one
SELECT id, session_id, template_id, reward, success_score, efficiency_score, judge_analysis, judge_model, prompt_tokens, completion_tokens, message_count, user_corrections, evaluated_at, created_at, components, judge_prompt_tokens, judge_completion_tokens FROM session_scores WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetSessionScore(ctx context.Context, sessionID string) (SessionScore, error) {
	row := q.queryRow(ctx, q.getSessionScoreStmt, getSessionScore, sessionID)
	var i SessionScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TemplateID,
		&i.Reward,
		&i.SuccessScore,
		&i.EfficiencyScore,
		&i.JudgeAnalysis,
		&i.JudgeModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.MessageCount,
		&i.UserCorrections,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.Components,
		&i.JudgePromptTokens,
		&i.JudgeCompletionTokens,
	)
	return i, err
}

const countSessionScores = `-- name: CountSessionScores :one
SELECT COUNT(*) FROM session_scores
`

func (q *Queries) CountSessionScores(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countSessionScoresStmt, countSessionScores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSessionScores = `-- name: ListSessionScores :many
SELECT id, session_id, template_id, reward, success_score, efficiency_score,
       judge_analysis, judge_model, prompt_tokens, completion_tokens,
       message_count, user_corrections, evaluated_at, created_at, components, judge_prompt_tokens, judge_completion_tokens
FROM session_scores
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListSessionScores(ctx context.Context, limit int64) ([]SessionScore, error) {
	rows, err := q.query(ctx, q.listSessionScoresStmt, listSessionScores, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionScore{}
	for rows.Next() {
		var i SessionScore
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TemplateID,
			&i.Reward,
			&i.SuccessScore,
			&i.EfficiencyScore,
			&i.JudgeAnalysis,
			&i.JudgeModel,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.MessageCount,
			&i.UserCorrections,
			&i.EvaluatedAt,
			&i.CreatedAt,
			&i.Components,
			&i.JudgePromptTokens,
			&i.JudgeCompletionTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionScore = `-- name: UpdateSessionScore :one
UPDATE session_scores
SET reward = ?,
    success_score = ?,
    efficiency_score = ?,
    prompt_tokens = ?,
    completion_tokens = ?,
    message_count = ?,
    user_corrections = ?,
    components = ?,
    evaluated_at = strftime('%s', 'now')
WHERE session_id = ?
RETURNING id, session_id, template_id, reward, success_score, efficiency_score, judge_analysis, judge_model, prompt_tokens, completion_tokens, message_count, user_corrections, evaluated_at, created_at, components, judge_prompt_tokens, judge_completion_tokens
`

type UpdateSessionScoreParams struct {
	Reward           float64 `json:"reward"`
	SuccessScore     float64 `json:"success_score"`
	EfficiencyScore  float64 `json:"efficiency_score"`
	PromptTokens     int64   `json:"prompt_tokens"`
	CompletionTokens int64   `json:"completion_tokens"`
	MessageCount     int64   `json:"message_count"`
	UserCorrections  int64   `json:"user_corrections"`
	Components       string  `json:"components"`
	SessionID        string  `json:"session_id"`
}

// Re-scores a session in place (explicit feedback). The row is UPDATEd, never
// re-inserted, so the insert-only UCB trigger cannot double count it; the
// update_ucb_after_rescore trigger applies just the reward delta.
func (q *Queries) UpdateSessionScore(ctx context.Context, arg UpdateSessionScoreParams) (SessionScore, error) {
	row := q.queryRow(ctx, q.updateSessionScoreStmt, updateSessionScore,
		arg.Reward,
		arg.SuccessScore,
		arg.EfficiencyScore,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.MessageCount,
		arg.UserCorrections,
		arg.Components,
		arg.SessionID,
	)
	var i SessionScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TemplateID,
		&i.Reward,
		&i.SuccessScore,
		&i.EfficiencyScore,
		&i.JudgeAnalysis,
		&i.JudgeModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.MessageCount,
		&i.UserCorrections,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.Components,
		&i.JudgePromptTokens,
		&i.JudgeCompletionTokens,
	)
	return i, err
}

const getSessionsTokenBaseline = `-- name: GetSessionsTokenBaseline :one
SELECT COALESCE(AVG(prompt_tokens + completion_tokens), 0) as baseline
FROM (
    SELECT prompt_tokens, completion_tokens
    FROM sessions
    WHERE id != ?
      AND parent_session_id IS NULL
      AND message_count >= 4
      AND prompt_tokens + completion_tokens > 0
    ORDER BY created_at DESC
    LIMIT ?
)
`

type GetSessionsTokenBaselineParams struct {
	ID    string `json:"id"`
	Limit int64  `json:"limit"`
}

// Token baseline from the sessions table itself (not session_scores), so it is
// available before any session has been scored: mean prompt+completion tokens
// of the most recent root sessions with at least 4 messages (>= 2 user turns
// and their replies), excluding the session being evaluated.
func (q *Queries) GetSessionsTokenBaseline(ctx context.Context, arg GetSessionsTokenBaselineParams) (float64, error) {
	row := q.queryRow(ctx, q.getSessionsTokenBaselineStmt, getSessionsTokenBaseline, arg.ID, arg.Limit)
	var baseline float64
	err := row.Scan(&baseline)
	return baseline, err
}

const insertSessionFeedbackEvent = `-- name: InsertSessionFeedbackEvent :one
INSERT INTO events (subject, content, metadata)
VALUES (?, ?, ?)
RETURNING id
`

type InsertSessionFeedbackEventParams struct {
	Subject  string `json:"subject"`
	Content  string `json:"content"`
	Metadata string `json:"metadata"`
}

// Explicit user feedback (/feedback good|bad) is stored as an event whose
// subject is "session_feedback:<session id>"; the payload lives in metadata.
func (q *Queries) InsertSessionFeedbackEvent(ctx context.Context, arg InsertSessionFeedbackEventParams) (int64, error) {
	row := q.queryRow(ctx, q.insertSessionFeedbackEventStmt, insertSessionFeedbackEvent, arg.Subject, arg.Content, arg.Metadata)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLatestSessionFeedback = `-- name: GetLatestSessionFeedback :one
SELECT metadata FROM events WHERE subject = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestSessionFeedback(ctx context.Context, subject string) (string, error) {
	row := q.queryRow(ctx, q.getLatestSessionFeedbackStmt, getLatestSessionFeedback, subject)
	var metadata string
	err := row.Scan(&metadata)
	return metadata, err
}

const insertSkill = `-- name: InsertSkill :one
INSERT INTO skill_library (
    id, title, content, source_session_id, source_template_id,
    task_type, usage_count, success_rate, is_active, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, 0, 0.0, 1, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, title, content, source_session_id, source_template_id, task_type, usage_count, success_rate, is_active, created_at, updated_at, status, confidence, judge_model, eval_count, reward_total
`

type InsertSkillParams struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	Content          string         `json:"content"`
	SourceSessionID  sql.NullString `json:"source_session_id"`
	SourceTemplateID sql.NullString `json:"source_template_id"`
	TaskType         string         `json:"task_type"`
}

func (q *Queries) InsertSkill(ctx context.Context, arg InsertSkillParams) (SkillLibrary, error) {
	row := q.queryRow(ctx, q.insertSkillStmt, insertSkill,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.SourceSessionID,
		arg.SourceTemplateID,
		arg.TaskType,
	)
	var i SkillLibrary
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.SourceSessionID,
		&i.SourceTemplateID,
		&i.TaskType,
		&i.UsageCount,
		&i.SuccessRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Confidence,
		&i.JudgeModel,
		&i.EvalCount,
		&i.RewardTotal,
	)
	return i, err
}

const listActiveSkillsByType = `-- name: ListActiveSkillsByType :many
SELECT id, title, content, source_session_id, source_template_id, task_type, usage_count, success_rate, is_active, created_at, updated_at, status, confidence, judge_model, eval_count, reward_total FROM skill_library
WHERE is_active = 1 AND (task_type = ? OR task_type = 'general')
ORDER BY success_rate DESC, usage_count DESC
LIMIT ?
`

type ListActiveSkillsByTypeParams struct {
	TaskType string `json:"task_type"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListActiveSkillsByType(ctx context.Context, arg ListActiveSkillsByTypeParams) ([]SkillLibrary, error) {
	rows, err := q.query(ctx, q.listActiveSkillsByTypeStmt, listActiveSkillsByType, arg.TaskType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillLibrary{}
	for rows.Next() {
		var i SkillLibrary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.SourceSessionID,
			&i.SourceTemplateID,
			&i.TaskType,
			&i.UsageCount,
			&i.SuccessRate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Confidence,
			&i.JudgeModel,
			&i.EvalCount,
			&i.RewardTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveSkills = `-- name: ListAllActiveSkills :many
SELECT id, title, content, source_session_id, source_template_id, task_type, usage_count, success_rate, is_active, created_at, updated_at, status, confidence, judge_model, eval_count, reward_total FROM skill_library
WHERE is_active = 1
ORDER BY success_rate DESC, usage_count DESC
`

func (q *Queries) ListAllActiveSkills(ctx context.Context) ([]SkillLibrary, error) {
	rows, err := q.query(ctx, q.listAllActiveSkillsStmt, listAllActiveSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillLibrary{}
	for rows.Next() {
		var i SkillLibrary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.SourceSessionID,
			&i.SourceTemplateID,
			&i.TaskType,
			&i.UsageCount,
			&i.SuccessRate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Confidence,
			&i.JudgeModel,
			&i.EvalCount,
			&i.RewardTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSkills = `-- name: CountActiveSkills :one
SELECT COUNT(*) FROM skill_library WHERE is_active = 1
`

func (q *Queries) CountActiveSkills(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countActiveSkillsStmt, countActiveSkills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementSkillUsage = `-- name: IncrementSkillUsage :exec
UPDATE skill_library
SET usage_count = usage_count + 1, updated_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) IncrementSkillUsage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.incrementSkillUsageStmt, incrementSkillUsage, id)
	return err
}

const getEvaluatorStats = `-- name: GetEvaluatorStats :one
SELECT
    (SELECT COUNT(*) FROM session_scores) as total_evaluations,
    (SELECT COALESCE(AVG(reward), 0.0) FROM session_scores) as avg_reward,
    (SELECT COUNT(*) FROM skill_library WHERE is_active = 1) as active_skills,
    (SELECT MAX(created_at) FROM session_scores) as last_evaluation
`

type GetEvaluatorStatsRow struct {
	TotalEvaluations int64         `json:"total_evaluations"`
	AvgReward        float64       `json:"avg_reward"`
	ActiveSkills     int64         `json:"active_skills"`
	LastEvaluation   sql.NullInt64 `json:"last_evaluation"`
}

func (q *Queries) GetEvaluatorStats(ctx context.Context) (GetEvaluatorStatsRow, error) {
	row := q.queryRow(ctx, q.getEvaluatorStatsStmt, getEvaluatorStats)
	var i GetEvaluatorStatsRow
	err := row.Scan(
		&i.TotalEvaluations,
		&i.AvgReward,
		&i.ActiveSkills,
		&i.LastEvaluation,
	)
	return i, err
}

const updateSessionScoreJudge = `-- name: UpdateSessionScoreJudge :exec
UPDATE session_scores
SET judge_analysis = ?,
    judge_model = ?,
    judge_prompt_tokens = ?,
    judge_completion_tokens = ?
WHERE session_id = ?
`

type UpdateSessionScoreJudgeParams struct {
	JudgeAnalysis         sql.NullString `json:"judge_analysis"`
	JudgeModel            sql.NullString `json:"judge_model"`
	JudgePromptTokens     int64          `json:"judge_prompt_tokens"`
	JudgeCompletionTokens int64          `json:"judge_completion_tokens"`
	SessionID             string         `json:"session_id"`
}

// Stores the LLM judge output on an existing score. It does not touch reward,
// so neither UCB trigger fires.
func (q *Queries) UpdateSessionScoreJudge(ctx context.Context, arg UpdateSessionScoreJudgeParams) error {
	_, err := q.exec(ctx, q.updateSessionScoreJudgeStmt, updateSessionScoreJudge,
		arg.JudgeAnalysis,
		arg.JudgeModel,
		arg.JudgePromptTokens,
		arg.JudgeCompletionTokens,
		arg.SessionID,
	)
	return err
}

const getJudgeUsageSince = `-- name: GetJudgeUsageSince :one
SELECT
    COUNT(*) as calls,
    CAST(COALESCE(SUM(judge_prompt_tokens + judge_completion_tokens), 0) AS INTEGER) as tokens
FROM session_scores
WHERE judge_model IS NOT NULL AND created_at >= ?
`

type GetJudgeUsageSinceRow struct {
	Calls  int64 `json:"calls"`
	Tokens int64 `json:"tokens"`
}

// Judge calls and tokens spent since a unix timestamp (start of the local day),
// derived from persisted scores so the daily budget survives restarts.
func (q *Queries) GetJudgeUsageSince(ctx context.Context, createdAt int64) (GetJudgeUsageSinceRow, error) {
	row := q.queryRow(ctx, q.getJudgeUsageSinceStmt, getJudgeUsageSince, createdAt)
	var i GetJudgeUsageSinceRow
	err := row.Scan(&i.Calls, &i.Tokens)
	return i, err
}

const insertSessionTemplateSelection = `-- name: InsertSessionTemplateSelection :exec
INSERT OR IGNORE INTO session_template_selections (session_id, section, variant_id, selected_at)
VALUES (?, ?, ?, strftime('%s', 'now'))
`

type InsertSessionTemplateSelectionParams struct {
	SessionID string `json:"session_id"`
	Section   string `json:"section"`
	VariantID string `json:"variant_id"`
}

// Prompt template variants: the DB holds selections and statistics only; the
// variant sources are files. variant_id is "<section>#<variant>".
// First writer wins, so concurrent processes agree on the frozen choice.
func (q *Queries) InsertSessionTemplateSelection(ctx context.Context, arg InsertSessionTemplateSelectionParams) error {
	_, err := q.exec(ctx, q.insertSessionTemplateSelectionStmt, insertSessionTemplateSelection, arg.SessionID, arg.Section, arg.VariantID)
	return err
}

const getSessionTemplateSelection = `-- name: GetSessionTemplateSelection :one
SELECT variant_id FROM session_template_selections WHERE session_id = ? AND section = ?
`

type GetSessionTemplateSelectionParams struct {
	SessionID string `json:"session_id"`
	Section   string `json:"section"`
}

func (q *Queries) GetSessionTemplateSelection(ctx context.Context, arg GetSessionTemplateSelectionParams) (string, error) {
	row := q.queryRow(ctx, q.getSessionTemplateSelectionStmt, getSessionTemplateSelection, arg.SessionID, arg.Section)
	var variant_id string
	err := row.Scan(&variant_id)
	return variant_id, err
}

const listVariantSelectionCounts = `-- name: ListVariantSelectionCounts :many
SELECT variant_id, COUNT(*) as selections
FROM session_template_selections
WHERE section = ?
GROUP BY variant_id
`

type ListVariantSelectionCountsRow struct {
	VariantID  string `json:"variant_id"`
	Selections int64  `json:"selections"`
}

func (q *Queries) ListVariantSelectionCounts(ctx context.Context, section string) ([]ListVariantSelectionCountsRow, error) {
	rows, err := q.query(ctx, q.listVariantSelectionCountsStmt, listVariantSelectionCounts, section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantSelectionCountsRow{}
	for rows.Next() {
		var i ListVariantSelectionCountsRow
		if err := rows.Scan(&i.VariantID, &i.Selections); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantStatsBySection = `-- name: ListVariantStatsBySection :many
SELECT variant_id, section, times_used, total_reward, avg_reward, updated_at
FROM prompt_variant_stats
WHERE section = ?
`

func (q *Queries) ListVariantStatsBySection(ctx context.Context, section string) ([]PromptVariantStat, error) {
	rows, err := q.query(ctx, q.listVariantStatsBySectionStmt, listVariantStatsBySection, section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptVariantStat{}
	for rows.Next() {
		var i PromptVariantStat
		if err := rows.Scan(&i.VariantID, &i.Section, &i.TimesUsed, &i.TotalReward, &i.AvgReward, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVariantStats = `-- name: ListAllVariantStats :many
SELECT variant_id, section, times_used, total_reward, avg_reward, updated_at
FROM prompt_variant_stats
ORDER BY section, variant_id
`

func (q *Queries) ListAllVariantStats(ctx context.Context) ([]PromptVariantStat, error) {
	rows, err := q.query(ctx, q.listAllVariantStatsStmt, listAllVariantStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptVariantStat{}
	for rows.Next() {
		var i PromptVariantStat
		if err := rows.Scan(&i.VariantID, &i.Section, &i.TimesUsed, &i.TotalReward, &i.AvgReward, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const applySessionRewardToVariantStats = `-- name: ApplySessionRewardToVariantStats :exec
INSERT INTO prompt_variant_stats (variant_id, section, times_used, total_reward, avg_reward, updated_at)
SELECT variant_id, section, 1, ?, ?, unixepoch()
FROM session_template_selections
WHERE session_id = ?
ON CONFLICT(variant_id) DO UPDATE SET
    times_used = times_used + 1,
    total_reward = total_reward + excluded.total_reward,
    avg_reward = (total_reward + excluded.total_reward) / (times_used + 1),
    updated_at = unixepoch()
`

type ApplySessionRewardToVariantStatsParams struct {
	TotalReward float64 `json:"total_reward"`
	AvgReward   float64 `json:"avg_reward"`
	SessionID   string  `json:"session_id"`
}

// Counts an evaluated session once for every variant it was served: one
// statement, joined to the session's selections.
func (q *Queries) ApplySessionRewardToVariantStats(ctx context.Context, arg ApplySessionRewardToVariantStatsParams) error {
	_, err := q.exec(ctx, q.applySessionRewardToVariantStatsStmt, applySessionRewardToVariantStats, arg.TotalReward, arg.AvgReward, arg.SessionID)
	return err
}

const applyRewardDeltaToVariantStats = `-- name: ApplyRewardDeltaToVariantStats :exec
UPDATE prompt_variant_stats
SET total_reward = total_reward + ?,
    avg_reward = (total_reward + ?) / MAX(times_used, 1),
    updated_at = unixepoch()
WHERE variant_id IN (SELECT variant_id FROM session_template_selections WHERE session_id = ?)
`

type ApplyRewardDeltaToVariantStatsParams struct {
	Delta     float64 `json:"delta"`
	Delta2    float64 `json:"delta_2"`
	SessionID string  `json:"session_id"`
}

// A re-score applies only the reward delta and never touches times_used.
func (q *Queries) ApplyRewardDeltaToVariantStats(ctx context.Context, arg ApplyRewardDeltaToVariantStatsParams) error {
	_, err := q.exec(ctx, q.applyRewardDeltaToVariantStatsStmt, applyRewardDeltaToVariantStats, arg.Delta, arg.Delta2, arg.SessionID)
	return err
}
