// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: self_improvement.sql

package db

import (
	"context"
	"database/sql"
)

const insertPromptTemplate = `-- name: InsertPromptTemplate :one
INSERT INTO prompt_templates (id, name, section, content, version, is_active, is_default, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, name, section, content, version, is_active, is_default, created_at, updated_at
`

type InsertPromptTemplateParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Section   string `json:"section"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	IsActive  int64  `json:"is_active"`
	IsDefault int64  `json:"is_default"`
}

func (q *Queries) InsertPromptTemplate(ctx context.Context, arg InsertPromptTemplateParams) (PromptTemplate, error) {
	row := q.queryRow(ctx, q.insertPromptTemplateStmt, insertPromptTemplate,
		arg.ID,
		arg.Name,
		arg.Section,
		arg.Content,
		arg.Version,
		arg.IsActive,
		arg.IsDefault,
	)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Section,
		&i.Content,
		&i.Version,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, name, section, content, version, is_active, is_default, created_at, updated_at FROM prompt_templates WHERE id = ? LIMIT 1
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id string) (PromptTemplate, error) {
	row := q.queryRow(ctx, q.getPromptTemplateStmt, getPromptTemplate, id)
	var i PromptTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Section,
		&i.Content,
		&i.Version,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTemplatesBySection = `-- name: ListActiveTemplatesBySection :many
SELECT
    pt.id,
    pt.name,
    pt.section,
    pt.content,
    pt.version,
    pt.is_active,
    pt.is_default,
    pt.created_at,
    pt.updated_at,
    COALESCE(us.avg_reward, 0.0) as avg_reward,
    COALESCE(us.times_used, 0) as times_used,
    COALESCE(us.ucb_score, 9999.0) as ucb_score
FROM prompt_templates pt
LEFT JOIN prompt_ucb_stats us ON pt.id = us.template_id
WHERE pt.section = ? AND pt.is_active = 1
ORDER BY us.ucb_score DESC, pt.name
`

type ListActiveTemplatesBySectionRow struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Section   string  `json:"section"`
	Content   string  `json:"content"`
	Version   int64   `json:"version"`
	IsActive  int64   `json:"is_active"`
	IsDefault int64   `json:"is_default"`
	CreatedAt int64   `json:"created_at"`
	UpdatedAt int64   `json:"updated_at"`
	AvgReward float64 `json:"avg_reward"`
	TimesUsed int64   `json:"times_used"`
	UcbScore  float64 `json:"ucb_score"`
}

func (q *Queries) ListActiveTemplatesBySection(ctx context.Context, section string) ([]ListActiveTemplatesBySectionRow, error) {
	rows, err := q.query(ctx, q.listActiveTemplatesBySectionStmt, listActiveTemplatesBySection, section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTemplatesBySectionRow{}
	for rows.Next() {
		var i ListActiveTemplatesBySectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Section,
			&i.Content,
			&i.Version,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvgReward,
			&i.TimesUsed,
			&i.UcbScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPromptTemplates = `-- name: CountPromptTemplates :one
SELECT COUNT(*) FROM prompt_templates WHERE is_active = 1
`

func (q *Queries) CountPromptTemplates(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countPromptTemplatesStmt, countPromptTemplates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertSessionScore = `-- name: InsertSessionScore :one
INSERT INTO session_scores (
    id, session_id, template_id, reward, success_score, efficiency_score,
    judge_analysis, judge_model, prompt_tokens, completion_tokens,
    message_count, user_corrections, evaluated_at, created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, session_id, template_id, reward, success_score, efficiency_score, judge_analysis, judge_model, prompt_tokens, completion_tokens, message_count, user_corrections, evaluated_at, created_at
`

type InsertSessionScoreParams struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	TemplateID       sql.NullString `json:"template_id"`
	Reward           float64        `json:"reward"`
	SuccessScore     float64        `json:"success_score"`
	EfficiencyScore  float64        `json:"efficiency_score"`
	JudgeAnalysis    sql.NullString `json:"judge_analysis"`
	JudgeModel       sql.NullString `json:"judge_model"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	MessageCount     int64          `json:"message_count"`
	UserCorrections  int64          `json:"user_corrections"`
}

func (q *Queries) InsertSessionScore(ctx context.Context, arg InsertSessionScoreParams) (SessionScore, error) {
	row := q.queryRow(ctx, q.insertSessionScoreStmt, insertSessionScore,
		arg.ID,
		arg.SessionID,
		arg.TemplateID,
		arg.Reward,
		arg.SuccessScore,
		arg.EfficiencyScore,
		arg.JudgeAnalysis,
		arg.JudgeModel,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.MessageCount,
		arg.UserCorrections,
	)
	var i SessionScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TemplateID,
		&i.Reward,
		&i.SuccessScore,
		&i.EfficiencyScore,
		&i.JudgeAnalysis,
		&i.JudgeModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.MessageCount,
		&i.UserCorrections,
		&i.EvaluatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionScore = `-- name: GetSessionScore :one
SELECT id, session_id, template_id, reward, success_score, efficiency_score, judge_analysis, judge_model, prompt_tokens, completion_tokens, message_count, user_corrections, evaluated_at, created_at FROM session_scores WHERE session_id = ? LIMIT 1
`

func (q *Queries) GetSessionScore(ctx context.Context, sessionID string) (SessionScore, error) {
	row := q.queryRow(ctx, q.getSessionScoreStmt, getSessionScore, sessionID)
	var i SessionScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TemplateID,
		&i.Reward,
		&i.SuccessScore,
		&i.EfficiencyScore,
		&i.JudgeAnalysis,
		&i.JudgeModel,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.MessageCount,
		&i.UserCorrections,
		&i.EvaluatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countSessionScores = `-- name: CountSessionScores :one
SELECT COUNT(*) FROM session_scores
`

func (q *Queries) CountSessionScores(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countSessionScoresStmt, countSessionScores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTokenBaseline = `-- name: GetTokenBaseline :one
SELECT COALESCE(AVG(prompt_tokens + completion_tokens), 0) as baseline
FROM (
    SELECT prompt_tokens, completion_tokens
    FROM session_scores
    ORDER BY created_at DESC
    LIMIT ?
)
`

func (q *Queries) GetTokenBaseline(ctx context.Context, limit int64) (float64, error) {
	row := q.queryRow(ctx, q.getTokenBaselineStmt, getTokenBaseline, limit)
	var baseline float64
	err := row.Scan(&baseline)
	return baseline, err
}

const getUCBStats = `-- name: GetUCBStats :one
SELECT template_id, times_used, total_reward, avg_reward, ucb_score, last_used_at, updated_at FROM prompt_ucb_stats WHERE template_id = ?
`

func (q *Queries) GetUCBStats(ctx context.Context, templateID string) (PromptUcbStat, error) {
	row := q.queryRow(ctx, q.getUCBStatsStmt, getUCBStats, templateID)
	var i PromptUcbStat
	err := row.Scan(
		&i.TemplateID,
		&i.TimesUsed,
		&i.TotalReward,
		&i.AvgReward,
		&i.UcbScore,
		&i.LastUsedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSkill = `-- name: InsertSkill :one
INSERT INTO skill_library (
    id, title, content, source_session_id, source_template_id,
    task_type, usage_count, success_rate, is_active, created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, 0, 0.0, 1, strftime('%s', 'now'), strftime('%s', 'now'))
RETURNING id, title, content, source_session_id, source_template_id, task_type, usage_count, success_rate, is_active, created_at, updated_at
`

type InsertSkillParams struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	Content          string         `json:"content"`
	SourceSessionID  sql.NullString `json:"source_session_id"`
	SourceTemplateID sql.NullString `json:"source_template_id"`
	TaskType         string         `json:"task_type"`
}

func (q *Queries) InsertSkill(ctx context.Context, arg InsertSkillParams) (SkillLibrary, error) {
	row := q.queryRow(ctx, q.insertSkillStmt, insertSkill,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.SourceSessionID,
		arg.SourceTemplateID,
		arg.TaskType,
	)
	var i SkillLibrary
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.SourceSessionID,
		&i.SourceTemplateID,
		&i.TaskType,
		&i.UsageCount,
		&i.SuccessRate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSkillsByType = `-- name: ListActiveSkillsByType :many
SELECT id, title, content, source_session_id, source_template_id, task_type, usage_count, success_rate, is_active, created_at, updated_at FROM skill_library
WHERE is_active = 1 AND (task_type = ? OR task_type = 'general')
ORDER BY success_rate DESC, usage_count DESC
LIMIT ?
`

type ListActiveSkillsByTypeParams struct {
	TaskType string `json:"task_type"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListActiveSkillsByType(ctx context.Context, arg ListActiveSkillsByTypeParams) ([]SkillLibrary, error) {
	rows, err := q.query(ctx, q.listActiveSkillsByTypeStmt, listActiveSkillsByType, arg.TaskType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillLibrary{}
	for rows.Next() {
		var i SkillLibrary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.SourceSessionID,
			&i.SourceTemplateID,
			&i.TaskType,
			&i.UsageCount,
			&i.SuccessRate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveSkills = `-- name: ListAllActiveSkills :many
SELECT id, title, content, source_session_id, source_template_id, task_type, usage_count, success_rate, is_active, created_at, updated_at FROM skill_library
WHERE is_active = 1
ORDER BY success_rate DESC, usage_count DESC
`

func (q *Queries) ListAllActiveSkills(ctx context.Context) ([]SkillLibrary, error) {
	rows, err := q.query(ctx, q.listAllActiveSkillsStmt, listAllActiveSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkillLibrary{}
	for rows.Next() {
		var i SkillLibrary
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.SourceSessionID,
			&i.SourceTemplateID,
			&i.TaskType,
			&i.UsageCount,
			&i.SuccessRate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSkills = `-- name: CountActiveSkills :one
SELECT COUNT(*) FROM skill_library WHERE is_active = 1
`

func (q *Queries) CountActiveSkills(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countActiveSkillsStmt, countActiveSkills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateLowestSkill = `-- name: DeactivateLowestSkill :exec
UPDATE skill_library SET is_active = 0, updated_at = strftime('%s', 'now')
WHERE id = (
    SELECT id FROM skill_library
    WHERE is_active = 1
    ORDER BY success_rate ASC, usage_count ASC
    LIMIT 1
)
`

func (q *Queries) DeactivateLowestSkill(ctx context.Context) error {
	_, err := q.exec(ctx, q.deactivateLowestSkillStmt, deactivateLowestSkill)
	return err
}

const incrementSkillUsage = `-- name: IncrementSkillUsage :exec
UPDATE skill_library
SET usage_count = usage_count + 1, updated_at = strftime('%s', 'now')
WHERE id = ?
`

func (q *Queries) IncrementSkillUsage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.incrementSkillUsageStmt, incrementSkillUsage, id)
	return err
}

const listUCBRanking = `-- name: ListUCBRanking :many
SELECT
    pt.id,
    pt.name,
    pt.section,
    pt.version,
    pt.is_default,
    COALESCE(us.times_used, 0) as times_used,
    COALESCE(us.avg_reward, 0.0) as avg_reward,
    COALESCE(us.ucb_score, 9999.0) as ucb_score,
    COALESCE(us.last_used_at, 0) as last_used_at
FROM prompt_templates pt
LEFT JOIN prompt_ucb_stats us ON pt.id = us.template_id
WHERE pt.is_active = 1
ORDER BY us.ucb_score DESC, pt.name
`

type ListUCBRankingRow struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Section    string  `json:"section"`
	Version    int64   `json:"version"`
	IsDefault  int64   `json:"is_default"`
	TimesUsed  int64   `json:"times_used"`
	AvgReward  float64 `json:"avg_reward"`
	UcbScore   float64 `json:"ucb_score"`
	LastUsedAt int64   `json:"last_used_at"`
}

func (q *Queries) ListUCBRanking(ctx context.Context) ([]ListUCBRankingRow, error) {
	rows, err := q.query(ctx, q.listUCBRankingStmt, listUCBRanking)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUCBRankingRow{}
	for rows.Next() {
		var i ListUCBRankingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Section,
			&i.Version,
			&i.IsDefault,
			&i.TimesUsed,
			&i.AvgReward,
			&i.UcbScore,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvaluatorStats = `-- name: GetEvaluatorStats :one
SELECT
    (SELECT COUNT(*) FROM session_scores) as total_evaluations,
    (SELECT COALESCE(AVG(reward), 0.0) FROM session_scores) as avg_reward,
    (SELECT COUNT(*) FROM skill_library WHERE is_active = 1) as active_skills,
    (SELECT MAX(created_at) FROM session_scores) as last_evaluation
`

type GetEvaluatorStatsRow struct {
	TotalEvaluations int64         `json:"total_evaluations"`
	AvgReward        float64       `json:"avg_reward"`
	ActiveSkills     int64         `json:"active_skills"`
	LastEvaluation   sql.NullInt64 `json:"last_evaluation"`
}

func (q *Queries) GetEvaluatorStats(ctx context.Context) (GetEvaluatorStatsRow, error) {
	row := q.queryRow(ctx, q.getEvaluatorStatsStmt, getEvaluatorStats)
	var i GetEvaluatorStatsRow
	err := row.Scan(
		&i.TotalEvaluations,
		&i.AvgReward,
		&i.ActiveSkills,
		&i.LastEvaluation,
	)
	return i, err
}
