// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_goals.sql

package db

import (
	"context"
	"database/sql"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO session_goals (
    id,
    session_id,
    objective,
    status,
    max_iterations,
    max_duration_seconds,
    started_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
) RETURNING
    id,
    session_id,
    objective,
    status,
    iteration,
    max_iterations,
    max_duration_seconds,
    started_at,
    completed_at,
    last_progress,
    next_step,
    blocked_reason,
    created_at
`

type CreateGoalParams struct {
	ID                 string `json:"id"`
	SessionID          string `json:"session_id"`
	Objective          string `json:"objective"`
	Status             string `json:"status"`
	MaxIterations      int64  `json:"max_iterations"`
	MaxDurationSeconds int64  `json:"max_duration_seconds"`
	StartedAt          int64  `json:"started_at"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (SessionGoal, error) {
	row := q.queryRow(ctx, q.createGoalStmt, createGoal,
		arg.ID,
		arg.SessionID,
		arg.Objective,
		arg.Status,
		arg.MaxIterations,
		arg.MaxDurationSeconds,
		arg.StartedAt,
	)
	var i SessionGoal
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Objective,
		&i.Status,
		&i.Iteration,
		&i.MaxIterations,
		&i.MaxDurationSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastProgress,
		&i.NextStep,
		&i.BlockedReason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoalsBySession = `-- name: DeleteGoalsBySession :exec
DELETE FROM session_goals
WHERE session_id = ?
`

func (q *Queries) DeleteGoalsBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteGoalsBySessionStmt, deleteGoalsBySession, sessionID)
	return err
}

const getActiveGoal = `-- name: GetActiveGoal :one
SELECT
    id,
    session_id,
    objective,
    status,
    iteration,
    max_iterations,
    max_duration_seconds,
    started_at,
    completed_at,
    last_progress,
    next_step,
    blocked_reason,
    created_at
FROM session_goals
WHERE session_id = ?
  AND status = 'running'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveGoal(ctx context.Context, sessionID string) (SessionGoal, error) {
	row := q.queryRow(ctx, q.getActiveGoalStmt, getActiveGoal, sessionID)
	var i SessionGoal
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Objective,
		&i.Status,
		&i.Iteration,
		&i.MaxIterations,
		&i.MaxDurationSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastProgress,
		&i.NextStep,
		&i.BlockedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getGoalBySession = `-- name: GetGoalBySession :one
SELECT
    id,
    session_id,
    objective,
    status,
    iteration,
    max_iterations,
    max_duration_seconds,
    started_at,
    completed_at,
    last_progress,
    next_step,
    blocked_reason,
    created_at
FROM session_goals
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetGoalBySession(ctx context.Context, sessionID string) (SessionGoal, error) {
	row := q.queryRow(ctx, q.getGoalBySessionStmt, getGoalBySession, sessionID)
	var i SessionGoal
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Objective,
		&i.Status,
		&i.Iteration,
		&i.MaxIterations,
		&i.MaxDurationSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastProgress,
		&i.NextStep,
		&i.BlockedReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateGoalProgress = `-- name: UpdateGoalProgress :one
UPDATE session_goals
SET
    last_progress = ?,
    next_step = ?,
    iteration = ?
WHERE id = ?
RETURNING
    id,
    session_id,
    objective,
    status,
    iteration,
    max_iterations,
    max_duration_seconds,
    started_at,
    completed_at,
    last_progress,
    next_step,
    blocked_reason,
    created_at
`

type UpdateGoalProgressParams struct {
	LastProgress sql.NullString `json:"last_progress"`
	NextStep     sql.NullString `json:"next_step"`
	Iteration    int64          `json:"iteration"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateGoalProgress(ctx context.Context, arg UpdateGoalProgressParams) (SessionGoal, error) {
	row := q.queryRow(ctx, q.updateGoalProgressStmt, updateGoalProgress,
		arg.LastProgress,
		arg.NextStep,
		arg.Iteration,
		arg.ID,
	)
	var i SessionGoal
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Objective,
		&i.Status,
		&i.Iteration,
		&i.MaxIterations,
		&i.MaxDurationSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastProgress,
		&i.NextStep,
		&i.BlockedReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateGoalStatus = `-- name: UpdateGoalStatus :one
UPDATE session_goals
SET
    status = ?,
    iteration = ?,
    last_progress = ?,
    next_step = ?,
    blocked_reason = ?,
    completed_at = ?
WHERE id = ?
RETURNING
    id,
    session_id,
    objective,
    status,
    iteration,
    max_iterations,
    max_duration_seconds,
    started_at,
    completed_at,
    last_progress,
    next_step,
    blocked_reason,
    created_at
`

type UpdateGoalStatusParams struct {
	Status        string         `json:"status"`
	Iteration     int64          `json:"iteration"`
	LastProgress  sql.NullString `json:"last_progress"`
	NextStep      sql.NullString `json:"next_step"`
	BlockedReason sql.NullString `json:"blocked_reason"`
	CompletedAt   sql.NullInt64  `json:"completed_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateGoalStatus(ctx context.Context, arg UpdateGoalStatusParams) (SessionGoal, error) {
	row := q.queryRow(ctx, q.updateGoalStatusStmt, updateGoalStatus,
		arg.Status,
		arg.Iteration,
		arg.LastProgress,
		arg.NextStep,
		arg.BlockedReason,
		arg.CompletedAt,
		arg.ID,
	)
	var i SessionGoal
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Objective,
		&i.Status,
		&i.Iteration,
		&i.MaxIterations,
		&i.MaxDurationSeconds,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastProgress,
		&i.NextStep,
		&i.BlockedReason,
		&i.CreatedAt,
	)
	return i, err
}
